import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {randomUUID} from 'node:crypto';import pg from 'pg';import {PublicKey} from '@solana/web3.js';
import {createCampaignIndexHandler} from './public-campaign-ingest.mjs';import {createPublicCampaignStore} from './public-campaign-store.mjs';import {PostgresRegistry} from '../registry/registry.mjs';import * as client from '../protocol-v2/client.mjs';import {encodeTerms,termsHash,OFFSETS} from '../protocol-v2/policy.mjs';import {discriminator} from '../cpmm.mjs';
const key=n=>new PublicKey(Buffer.alloc(32,n));
function fixture(){
 const program=key(2),genesis=key(3),creator=key(4),vector=JSON.parse(readFileSync(new URL('../protocol-v2/test-vectors.json',import.meta.url))).termsHash.find(v=>v.name==='standard'),time=1790000000;
 const t={...vector.terms,genesis:client.keyHex(genesis),creator:client.keyHex(creator),opensAt:String(time-10),deadline:String(time+100),launchDeadline:String(time+1000),ammProgram:client.keyHex(client.RAYDIUM_CPMM)},campaign=client.campaignAddress(program,creator,t.nonce),bytes=Buffer.alloc(client.CAMPAIGN_LEN);client.CAMPAIGN_MAGIC.copy(bytes);encodeTerms(t).copy(bytes,8);termsHash(bytes.subarray(8,808)).copy(bytes,808);bytes.writeBigUInt64LE(1n,OFFSETS.receiptCount);bytes.writeBigUInt64LE(900000000n,OFFSETS.total);
 const clock=Buffer.alloc(40);clock.writeBigInt64LE(BigInt(time),32);const fee=Buffer.alloc(236);discriminator('account:AmmConfig').copy(fee);fee.writeBigUInt64LE(25000n,12);
 const account=(data,owner)=>({owner:String(owner),executable:false,data:[data.toString('base64'),'base64']}),id={genesisHash:String(genesis),programId:String(program),campaign:String(campaign)},commits=[],calls=[],state={slot:100,previous:{revision:0,body:null},badClock:false,badOwner:false,badFee:false};
 const rpc={async call(method,params){calls.push(method);assert.equal(params.at(-1).commitment,'finalized');return method==='getAccountInfo'?{context:{slot:100},value:account(bytes,program)}:{context:{slot:state.slot},value:[account(bytes,state.badOwner?key(9):program),account(clock,state.badClock?key(9):'Sysvar1111111111111111111111111111111111111'),state.badFee?null:account(fee,client.RAYDIUM_CPMM),null]};}};
 const store={snapshot:async()=>state.previous,commit:async x=>commits.push(x)},handler=createCampaignIndexHandler({store,rpc,...id,programVersion:3}),job={...id,jobClass:'campaign-index',operationKey:'campaign:0'},ctx={campaign:id,now:()=>time*1000,fenced:async(_,fn)=>fn()};return {id,state,bytes,clock,fee,commits,calls,handler,job,ctx};
}
test('current directory projection reads one finalized context, real cap totals and current AMM fee',async()=>{
 const f=fixture();await f.handler.run(f.job,f.ctx);const v=f.commits[0].body.view;assert.equal(v.phase,'open');assert.equal(v.totals.totalLamports,'900000000');assert.equal(v.totals.receiptCount,'1');assert.equal(v.source.commitment,'finalized');assert.equal(v.terms.tradeFeeBps,250);assert.equal(v.totals.settledAcceptedLamports,null);assert.deepEqual(f.calls,['getAccountInfo','getMultipleAccounts']);
 const unavailable=fixture();unavailable.state.badFee=true;await unavailable.handler.run(unavailable.job,unavailable.ctx);assert.equal(unavailable.commits[0].body.view.terms.tradeFeeBps,null,'missing actual config never displays expected fees');
});
test('projection rejects wrong ownership, stale clocks, backwards contexts and sequence gaps',async()=>{
 for(const mutate of [f=>f.state.badOwner=true,f=>f.state.badClock=true,f=>f.state.slot=99,f=>f.clock.writeBigInt64LE(1789999000n,32),f=>f.job.operationKey='campaign:2',f=>f.ctx.campaign={...f.id,genesisHash:String(key(9))}]){const f=fixture();mutate(f);await assert.rejects(f.handler.run(f.job,f.ctx));assert.equal(f.commits.length,0);}
 const f=fixture();f.state.previous={revision:1,body:{sequence:'0'}};assert.equal((await f.handler.run(f.job,f.ctx)).replayed,true);assert.equal(f.calls.length,0);
});
test('shared finalized directory snapshot survives restart, updates filters atomically and never resets stale freshness',{skip:!process.env.KIDS_TEST_POSTGRES_URL},async()=>{
 const schema='kids_test_'+randomUUID().replaceAll('-',''),control=new pg.Pool({connectionString:process.env.KIDS_TEST_POSTGRES_URL,max:1});let pool;
 try{await control.query(`CREATE SCHEMA ${schema}`);pool=new pg.Pool({connectionString:process.env.KIDS_TEST_POSTGRES_URL,max:2,options:`-c search_path=${schema}`});const registry=new PostgresRegistry({pool});await registry.migrate();const f=fixture();await f.handler.run(f.job,f.ctx);const body=f.commits[0].body;body.view.source.chainTimeUnix=Math.floor(Date.now()/1000);
  await registry.campaigns.upsert({...f.id,mode:'standard',campaignVersion:3,registryStatus:'planned',termsHash:body.termsHash});const created=(await registry.jobs.enqueue(f.job)).job,job=await registry.jobs.leaseById({jobId:created.jobId,token:created.fencingToken,owner:'test',ttlMs:30000});let now=Date.now();const store=createPublicCampaignStore(registry,{now:()=>now}),input={...f.commits[0],job,body};await store.commit(input);
  assert.equal((await registry.campaigns.list({status:'open'})).campaigns.length,1);assert.equal((await store.read(f.id)).available,true);assert.equal((await createPublicCampaignStore(registry).read(f.id)).totals.totalLamports,'900000000');const at=(await store.read(f.id)).readAt;now+=46000;assert.equal((await store.read(f.id)).available,false);now-=45000;assert.equal((await store.read(f.id)).readAt,at,'reading is not a new observation');
  await assert.rejects(store.commit(input),{code:'CAMPAIGN_CURSOR_CONFLICT'});assert.equal((await registry.jobs.listForCampaign(f.id)).filter(j=>j.operationKey==='campaign:1').length,1);
  await assert.rejects(store.commit({...input,expectedRevision:1,body:{...body,view:{...body.view,source:{...body.view.source,slot:99}}}}),/regressed/);assert.equal((await store.snapshot(f.id)).revision,1);
  await registry.jobs.complete({jobId:job.jobId,token:job.fencingToken,result:{outcome:'done'}});await assert.rejects(store.commit({...input,expectedRevision:1}),{code:'STALE_LEASE'});
  assert.equal((await store.read({...f.id,campaign:String(key(9))})).available,false);
 }finally{await pool?.end();await control.query(`DROP SCHEMA ${schema} CASCADE`);await control.end();}
});
