import {useEffect,useState} from 'react';
async function request(csrf){const r=await fetch('/api/admin/active-launch',{method:csrf?'POST':'GET',headers:csrf?{'Content-Type':'application/json','X-Kids-CSRF':csrf}:{},body:csrf?'{}':undefined,signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Active launch unavailable');return data;}
export function ActiveLaunchControl({csrf}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tick,setTick]=useState(0);const running=data?.job?.status==='running';
 useEffect(()=>{let active=true;async function refresh(){try{const next=await request();if(active){setData(next);setError('');}}catch(e){if(active){setData(null);setError(e.message);}}}refresh();const timer=setInterval(refresh,running?2000:15000);return()=>{active=false;clearInterval(timer);};},[running,tick]);
 const c=data?.campaign,ready=c?.phase==='awaiting-launch'&&BigInt(c.totalLamports)>=BigInt(c.softCapLamports)&&c.chainTimeUnix<c.launchDeadlineUnix;
 async function launch(){if(busy||running||!ready)return;setBusy(true);setError('');try{setData(await request(csrf));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section><div className="admin-heading"><div><h2>Active Shartcoin launch</h2><p>V3 escrow · Isolated localnet</p></div><button onClick={()=>setTick(n=>n+1)}>Refresh</button></div>{error&&<p role="alert">{error}</p>}{c?.configured&&<><div className="launch-test-totals"><p><strong>{(Number(c.totalLamports)/1e9).toLocaleString(undefined,{maximumFractionDigits:6})} SOL</strong>committed</p><p><strong>{Number(c.softCapLamports)/1e9}–{Number(c.hardCapLamports)/1e9} SOL</strong>accepted range</p><p><strong>{c.phase}</strong>on-chain status</p></div><p>Funding closes {new Date(c.deadlineUnix*1000).toLocaleString()}. Launch deadline: {new Date(c.launchDeadlineUnix*1000).toLocaleString()}.</p><button className="primary" disabled={!ready||busy||running} onClick={launch}>{running||busy?'Launching…':c.phase==='launched'?'Pool launched':'Launch local pool'}</button><p className="small muted">Launch settles allocations, creates the pool and locks liquidity atomically. Below the soft cap or after a missed launch deadline, participants can reclaim their SOL.</p>{data.job&&<p role="status" style={{overflowWrap:'anywhere'}}>{data.job.error||data.job.signature||data.job.status}</p>}<details><summary>Active program and mint</summary>{['escrowAddress','mint','programId'].map(key=><label key={key}>{key}<input readOnly value={c[key]}/></label>)}</details></>}</section>;
}
