import {ActiveLaunchControl} from './ActiveLaunchControl';
import {useEffect,useState} from 'react';
import {CoinUpdates} from './CoinUpdates';
import './admin.css';
import {LaunchRehearsal} from './LaunchRehearsal';
async function api(path,body,csrf){const response=await fetch('/api/admin/'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-Kids-CSRF':csrf}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});if(!response.headers.get('content-type')?.includes('application/json'))throw Error('The local operator service is unavailable');const result=await response.json();if(!response.ok)throw Error(result.error||result.detail||'Request failed');return result;}
export function Admin(){
 const [roundId,setRoundId]=useState('local-001'),[duration,setDuration]=useState(60);
 const [state,setState]=useState(null),[draft,setDraft]=useState(null),[health,setHealth]=useState(null),[tab,setTab]=useState('Overview'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){const next=await api('state');setState(next);setDraft(next.config);}
 useEffect(()=>{refresh().catch(e=>setError(e.message));},[]);
 async function run(action){setBusy(true);setError('');setNotice('');try{await action();}catch(e){setError(e.message);throw e;}finally{setBusy(false);}}
 function click(action){run(action).catch(()=>{});}
 async function content(action,payload){const preview=await api('content',{action,payload,revision:state.preview.revision,requestId:crypto.randomUUID()},state.csrf);setState(s=>({...s,preview}));setNotice('Saved.');}
 return <div className="kids-admin"><div className="admin-heading"><div><p className="eyebrow">KIDS / LOCAL OPERATOR</p><h1>Control room</h1><p>Localnet · Settings and content for this installation</p></div><button disabled={busy} onClick={()=>click(refresh)}>Refresh</button></div>
 <nav aria-label="Admin sections">{['Overview','Settings','Coin content','Activity'].map(name=><button className={tab===name?'active':''} key={name} onClick={()=>setTab(name)}>{name}</button>)}</nav>
 {error&&<p role="alert" className="warning">{error}{error.includes("Operator access")&&<> <a href="/__operator">Sign in as operator</a></>}</p>}{notice&&<p role="status">{notice}</p>}
 {!state?<p>Loading operator service…</p>:<>
 {tab==='Overview'&&<><div className="admin-grid"><section><h2>Earlier localnet setup</h2><p>{state.config?'Local validator configured':'Localnet setup is not complete'}</p><button disabled={busy||!state.config} onClick={()=>click(async()=>setHealth(await api('health')))}>Check validator & mints</button>{health&&<><p>Finalized slot <strong>{health.slot.toLocaleString()}</strong></p><p>Admin balance <strong>{(health.adminLamports/1e9).toLocaleString()} SOL</strong></p>{health.mints.map(m=><p key={m.symbol}>{m.symbol} <span className="admin-good">Verified SPL mint</span></p>)}</>}</section><section><h2>Launch readiness</h2><dl><dt>Opening pool range</dt><dd>$40K soft cap → $200K hard cap</dd><dt>Parent eligibility</dt><dd>≥0.05% of parent supply at snapshot</dd><dt>Escrow & refunds</dt><dd>Active v3 · Localnet :19099; legacy v1 refunds retained</dd><dt>Parent claims</dt><dd>Active snapshots configured; claims open after launch</dd><dt>Vanity mint worker</dt><dd>Separate Railway kids worker</dd></dl><p className="small muted">Public deposits remain closed. The post-launch rehearsal verifies a separate localnet pool and claims; it is not the active Shartcoin campaign.</p></section></div>{state.releaseGates&&<section><h2>Mainnet release gates</h2><p>Private localnet is running. Real-money deposits remain disabled.</p><dl>{state.releaseGates.blockingRequirements.map(item=><div key={item.id}><dt>{item.status==='partial'?'Partially verified':'Outstanding'}</dt><dd>{item.requirement}</dd></div>)}</dl></section>}<ActiveLaunchControl csrf={state.csrf}/><LaunchRehearsal csrf={state.csrf}/><section><h2>Test identities</h2>{Object.entries(state.config?.wallets||{}).map(([name,address])=><label key={name}>{name}<input readOnly value={address}/></label>)}<p className="small muted">Keys stay in the local runtime directory. These addresses hold local test SOL and tokens.</p></section></>}
 {tab==='Settings'&&draft&&<form onSubmit={e=>{e.preventDefault();click(async()=>{const result=await api('settings',{revision:state.revision,config:draft},state.csrf);setState(s=>({...s,...result}));setDraft(result.config);setNotice('Configuration saved.');});}}><section><h2>Earlier localnet addresses</h2><p>Replace test mints with other verified localnet mints. Changing a setting does not migrate existing allocations.</p><label>Admin wallet<input required value={draft.admin} onChange={e=>setDraft({...draft,admin:e.target.value})}/></label><div className="admin-grid">{Object.entries(draft.mints).map(([symbol,address])=><label key={symbol}>{symbol==='SHART'?'Shartcoin':symbol} mint<input required value={address} onChange={e=>setDraft({...draft,mints:{...draft.mints,[symbol]:e.target.value}})}/></label>)}</div></section><section><h2>Prelaunch economics</h2><label>Local SOL reference price · USD<input type="number" min="0.01" step="0.01" required value={draft.launch.solUsd} onChange={e=>setDraft({...draft,launch:{...draft.launch,solUsd:Number(e.target.value)}})}/></label><p>Retained SOL cap: {draft.launch.solUsd>0?(100000/draft.launch.solUsd).toLocaleString(): '—'} SOL</p><p>Parent reserve 10% · 5% per community · Holder threshold 0.05%</p><h3>Raydium CPMM · $Shartcoin / SOL</h3><p><strong>{draft.launch.pool.tradeFeeBps/100}% trading fee</strong> · 1.68% to LPs · 0.32% to Raydium</p><p>Permanent liquidity lock · Fee collection retained · No token transfer tax</p><p>Supply: 43.5% prelaunch · 43.5% liquidity · 10% parents · 3% dev</p><p>Dev supply: 1% unlocked at launch · 2% linear over 3 months · No cliff. Active v3 vesting starts at launch. The post-launch preview shows a separate funded local test pool.</p><p>LP earnings: 98/168 KIDS treasury · 20/168 dev · 25/168 each parent buyback and burn. Fee routing is verified in the separate localnet rehearsal only; public trading is not enabled.</p><button className="primary" disabled={busy}>Save configuration</button></section></form>}
 {tab==='Submissions'&&<section><h2>Review queue</h2>{!state.submissions?.length&&!state.preview.history.length?<p>No submissions yet.</p>:[...(state.submissions||[]),...state.preview.history].map(p=><article className="admin-proposal" key={(p.owner||'legacy')+p.id+':'+p.version}><div><h3>{p.name} · ${p.ticker}</h3><p>{p.a} × {p.b} · Version {p.version}</p><p>{p.description}</p><span>{p.status}</span></div>{p.status==='Awaiting review'&&<div className="admin-actions">{['Approved for next round','Changes requested'].map(status=><button key={status} disabled={busy} onClick={()=>click(async()=>{if(p.owner){await api('moderate',{owner:p.owner,id:p.id,version:p.version,status},state.csrf);await refresh();setNotice('Review saved.');}else await content('review',{id:p.id,version:p.version,status});})}>{status}</button>)}</div>}</article>)}<p className="small muted">Wallet-owned submissions and earlier local records. Approval preserves the submitted version.</p></section>}
 {tab==='Rounds'&&<section><h2>Voting rounds</h2><p>Freeze every approved wallet submission and take a finalized KIDS holder snapshot. The configured admin treasury is excluded from voting power.</p><form onSubmit={e=>{e.preventDefault();click(async()=>{await api('round/open',{id:roundId,durationMinutes:duration},state.csrf);await refresh();setNotice('Round opened with an immutable ballot and holder snapshot.');});}}><div className="admin-grid"><label>Round ID<input required pattern="[A-Za-z0-9-]{1,40}" value={roundId} onChange={e=>setRoundId(e.target.value)}/></label><label>Duration · minutes<input required type="number" min="1" max="10080" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></label></div><button className="primary" disabled={busy||!state.config}>Freeze & open round</button></form>{state.rounds?.map(r=><article className="admin-proposal" key={r.id}><div><h3>{r.id}</h3><p>{r.candidates.length} candidates · Snapshot slot {r.snapshot.slot}</p><p>{r.result?.status||'Closes '+new Date(r.closesAt).toLocaleString()}</p></div><button disabled={busy||!!r.result||Date.now()<r.closesAt} onClick={()=>click(async()=>{await api('round/close',{id:r.id},state.csrf);await refresh();setNotice('Round result recorded.');})}>Finalize result</button></article>)}</section>}
 {tab==='Coin content'&&<CoinUpdates admin profile={state.preview.coinProfile} posts={state.preview.coinPosts||[]} onAction={(action,payload)=>run(()=>content(action,payload))} ready={!busy}/>}
 {tab==='Activity'&&<section><h2>Operator activity</h2>{state.audit.length?state.audit.map(event=><article className="admin-event" key={event.id}><strong>{event.action}</strong><time>{new Date(event.time).toLocaleString()}</time><code>{event.detail}</code></article>):<p>No operator changes recorded yet.</p>}</section>}
 </>}
 </div>;
}
