import {resolveShartVideo} from './coin-media';
import {useState} from 'react';
import {DEFAULT_COIN_DESCRIPTION,resolveCoinDescription,resolveCoinAuthor,resolveCoinPost} from './coin-display';
export function CoinUpdates({profile,posts,onAction,ready,admin=false}){
 const [editing,setEditing]=useState(false),[draft,setDraft]=useState(null),[text,setText]=useState(''),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const current=profile?{...profile,description:resolveCoinDescription(profile.description)}:{description:DEFAULT_COIN_DESCRIPTION,banner:'',logo:'',xUrl:'',websiteUrl:''};
 const featuredVideo=resolveShartVideo(current.video);
 async function image(event,key){const file=event.target.files?.[0];if(!file)return;if(!['image/png','image/webp'].includes(file.type)||file.size>1000000)return setError('Choose a PNG or WebP under 1 MB.');const reader=new FileReader();reader.onload=()=>setDraft(d=>({...d,[key]:reader.result}));reader.onerror=()=>setError('Image could not be read.');reader.readAsDataURL(file);}
 async function uploadVideo(event){const file=event.target.files?.[0];if(!file)return;if(!['video/mp4','video/webm'].includes(file.type)||file.size>10000000)return setError('Choose an MP4 or WebM under 10 MB.');setError('');const reader=new FileReader();reader.onload=()=>setDraft(d=>({...d,video:reader.result}));reader.onerror=()=>setError('Could not read the video. Try again.');reader.readAsDataURL(file);}
 async function save(action,payload){setBusy(true);setError('');try{await onAction(action,payload);if(action==='coin-post'){setText('');setUrl('');}else {setEditing(false);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="coin-community" id="shart-updates"><details className="coin-about"><summary>About Shartcoin</summary><p>{current.description}</p></details><div className="updates-heading"><h2>Dev updates</h2><span>Dev posts</span></div>
 {admin&&<details className="demo-owner"><summary>Dev controls</summary><p className="small muted">Local operator controls. Changes are saved to this installation.</p><button disabled={!ready||busy} onClick={()=>{setDraft({...current,video:featuredVideo});setEditing(!editing);}}>Edit coin profile</button>
 {editing&&draft&&<div className="profile-editor"><label>Banner · PNG or WebP, under 1 MB<input type="file" accept="image/png,image/webp" onChange={e=>image(e,'banner')}/></label>{draft.banner&&<img className="banner-preview" src={draft.banner} alt="Banner preview"/>}<label>Logo · PNG or WebP, under 1 MB<input type="file" accept="image/png,image/webp" onChange={e=>image(e,'logo')}/></label>{draft.logo&&<img className="logo-preview" src={draft.logo} alt="Logo preview"/>}<label>Coin description<textarea maxLength={1200} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>X profile URL<input type="url" placeholder="https://x.com/yourcoin" value={draft.xUrl||''} onChange={e=>setDraft({...draft,xUrl:e.target.value})}/></label><label>Website URL<input type="url" placeholder="https://yourcoin.com" value={draft.websiteUrl||''} onChange={e=>setDraft({...draft,websiteUrl:e.target.value})}/></label><label>Featured video · Optional<input type="file" accept="video/mp4,video/webm" onChange={uploadVideo}/><small>MP4 or WebM · Up to 10 MB</small></label><label>Or direct video URL<input type="url" placeholder="https://your-site.com/video.mp4" value={draft.video?.startsWith('data:')?'':draft.video||''} onChange={e=>setDraft({...draft,video:e.target.value})}/></label>{draft.video&&<div><video className="dev-video-preview" controls playsInline preload="metadata" src={draft.video}/><button onClick={()=>setDraft({...draft,video:''})}>Remove video</button></div>}<button disabled={busy||!ready} onClick={()=>save('coin-profile',draft)}>Save profile</button></div>}
 <div className="post-composer"><label>Write an update<textarea maxLength={2000} placeholder="What’s happening with Shartcoin?" value={text} onChange={e=>setText(e.target.value)}/></label><label>Video, X post, or other HTTPS link<input type="url" placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></label><button className="primary" disabled={busy||!ready||(!text.trim()&&!url)} onClick={()=>save('coin-post',{text,url})}>{busy?'Saving…':"Publish update"}</button></div>{error&&<p className="warning" role="alert">{error}</p>}</details>}
 <div className="coin-feed">{posts.length?posts.map(post=><article key={post.id}><div className="post-author"><span className="mini-logo">S!</span><div><strong>{resolveCoinAuthor(post.author).replace(/Owner/g,'Dev').replace(/owner/g,'dev')}</strong><time dateTime={post.createdAt}>{new Date(post.createdAt).toLocaleString()}</time></div></div>{post.text&&<p>{resolveCoinPost(post.text)}</p>}{post.url&&(/\.(mp4|webm)(\?|$)/i.test(post.url)?<video controls preload="none" src={post.url} aria-label="Dev video update"/>:<a href={post.url} target="_blank" rel="noopener noreferrer">{new URL(post.url).hostname==='x.com'||new URL(post.url).hostname==='twitter.com'?'View post on X':'Open linked update'} ↗</a>)}</article>):<div className="feed-empty"><strong>No dev updates yet.</strong><p>Updates will appear here as the launch takes shape.</p></div>}</div></section>;
}
