import {useEffect,useState} from 'react';
import {accountApi} from './Account';
import './dev-vesting.css';
export function DevVesting({identity,onSignIn}) {
 const [state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState('');
 async function refresh(){try{setState(await accountApi('dev-vesting'));setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{let active=true;async function read(){try{const result=await accountApi('dev-vesting');if(active){setState(result);setError('');}}catch(e){if(active)setError(e.message);}}read();const id=setInterval(read,15000);return()=>{active=false;clearInterval(id);};},[]);
 const amount=raw=>(Number(raw||0)/10**(state?.decimals||6)).toLocaleString(undefined,{maximumFractionDigits:2});
 async function claim(){if(busy)return;setBusy(true);setError('');try{const session=await accountApi('state');const result=await accountApi('dev-vesting/claim',{},session.csrf);setState(result.state);setReceipt(result.signature);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <details className="dev-vesting"><summary><strong>Dev allocation · 3%</strong><span>1% at launch + 2% over 3 months</span></summary><div className="dev-vesting-body"><p className="small muted">Localnet vesting test · Separate from the prelaunch funding preview</p>{state?.funded?<><div className="dev-vesting-stats"><div><span>Claimable Shartcoin</span><strong>{amount(state.claimableRaw)}</strong></div><div><span>Claimed</span><strong>{amount(state.claimedRaw)}</strong></div><div><span>Total dev allocation</span><strong>{amount(state.totalRaw)}</strong></div></div><progress aria-label="Dev allocation claimed" max={Number(state.totalRaw)} value={Number(state.claimedRaw)}/><p className="small">Linear vesting ends {new Date(state.end*1000).toLocaleDateString()} · No cliff · Non-revocable</p><p className="small dev-wallet">Dev wallet: {state.dev}</p>{!identity?.owner?<button className="outlined" onClick={onSignIn}>Sign in to claim</button>:identity.owner===state.dev?<button className="primary" disabled={busy||BigInt(state.claimableRaw)<=0n} onClick={claim}>{busy?'Confirming claim…':'Claim vested Shartcoin'}</button>:<p className="small muted">Only the designated dev wallet can claim.</p>}{receipt&&<p role="status" className="small dev-wallet">Confirmed on localnet: {receipt}</p>}</>:<p>{error?'Vesting data unavailable.':'Loading on-chain vesting…'}</p>}{error&&<p role="alert" className="warning">{error}</p>}<button className="text-button" disabled={busy} onClick={refresh}>Refresh balances</button></div></details>;
}
