export const DOCS = [
 {id:'start',group:'Start here',title:'A fairer place to start.',summary:'Two communities. One new coin. Understand the rules before you commit.',sections:[
  {title:'What is KIDS?',paragraphs:['KIDS is a launchpad built around a simple idea: getting there first should not decide the price you pay. A timed commitment window replaces a rising bonding curve. Accepted participants receive tokens at the same allocation rate within that campaign.','The first format brings two existing communities together to create a new coin. Shartcoin brings together Fartcoin and Buttcoin. The pink dog belongs to KIDS, the platform; Shartcoin has its own identity.']},
  {title:'The short version',steps:['Read the coin’s terms, parent communities, caps and closing time.','Commit SOL to the campaign’s on-chain escrow. Your wallet signs the transaction.','After funding closes, the campaign settles: launch if its conditions are met, or refunds if it fails.','Claim your purchased tokens and any refundable SOL. Eligible parent holders have a separate reward claim.']},
  {title:'Start with your question',links:[['How does my commitment work?','commit'],['Do I qualify for parent rewards?','parents'],['Where do trading fees go?','fees'],['What can I verify myself?','verify']]}
 ]},
 {id:'why',group:'Start here',title:'Why we are building KIDS',summary:'A fair game should be a mechanism you can inspect, not a promise you have to trust.',sections:[
  {title:'The game we wanted to play',paragraphs:['A person with an idea and a community should have a chance to build something without access to a private group chat. KIDS starts with that ambition: visible allocations, a shared commitment window and rules people can inspect.','The name is a reminder to keep asking “is that fair?” The beanie-wearing pink dog is the platform’s flag for that attitude. The tone is playful; the accounting should be precise.']},
  {title:'Communities can build together',paragraphs:['A kid connects two parent communities. Each parent has a defined reward reserve, and part of collected liquidity-fee earnings is assigned to parent buybacks and burns. This creates a connection beyond putting two names on a banner. It does not guarantee demand, trading activity or a higher price.']},
  {title:'What fairness means here',paragraphs:['Timing within an open commitment window does not give a better allocation rate. Proportional allocation also removes an allocation advantage from simply dividing the same SOL across more wallets, apart from integer rounding.','It does not make wealth equal, stop every abusive identity, eliminate secondary-market bots or prevent losses. A large commitment can still receive a large allocation. Do not mistake a fairer launch mechanism for a risk-free coin.']},
  {title:'Build it in public',paragraphs:['Our goal is for people to inspect the rules, source and actual deployment. Published code, verified deployment and independent security review are different milestones. A missing verification should be visible, not replaced by a reassuring badge.']}
 ]},
 {id:'commit',group:'Using KIDS',title:'Commit, allocate, refund',summary:'Your commitment goes to program-controlled escrow. Final allocation is decided when funding closes.',sections:[
  {title:'Before signing',paragraphs:['Check the network, coin mint, campaign, SOL caps and closing time on the coin page. The approved transaction should deposit into the campaign escrow, not send your commitment to a dev’s personal wallet. Keep enough SOL outside the commitment for transaction fees and account rent.','Escrow is controlled by program rules. If a program is upgradeable, its upgrade authority is a separate trust consideration; a program-controlled account alone is not proof of immutability.']},
  {title:'Three funding outcomes',table:{headers:['At close','What happens'],rows:[['Below soft cap','Launch fails; the commitment becomes refundable.'],['Soft cap met, no more than hard cap','Commitments are accepted, subject to the campaign’s launch conditions.'],['Above hard cap','Acceptance scales proportionally; excess SOL becomes refundable.']]}},
  {title:'An oversubscribed example',paragraphs:['Illustration: a campaign has a 100 SOL soft cap, 500 SOL hard cap and 750 SOL committed. You committed 15 SOL. The campaign accepts 500 of 750 SOL, so approximately 10 of your 15 SOL is accepted and 5 SOL is refundable.','In this cleanly divisible example, your share of the participant reserve is 10 / 500 = 2%. With a one-billion-token original supply, the 43.5% participant reserve contains 435 million tokens; your allocation is approximately 8.7 million tokens. Actual token claims use accepted amounts recorded in settled receipts. Integer rounding can leave small refundable differences and reduce the aggregate accepted amount below the hard cap. These are illustrative values, not live campaign terms.']},
  {title:'What the caps describe',paragraphs:['The soft cap is the minimum accepted SOL needed for a successful launch. The hard cap limits SOL accepted into liquidity; oversubscription can exceed it because excess commitments are refundable.','A $40K–$200K total opening-pool target describes both sides together: $20K–$100K of SOL plus an initially equal-valued token side. USD estimates depend on the conversion used for that campaign. SOL amounts recorded in its terms govern; a dollar label is not a guaranteed future valuation.']},
  {title:'Refunds and launch failures',paragraphs:['A refundable balance must be paid by a successful on-chain refund transaction. “Refundable” does not mean it has already arrived in your wallet. Unpaid refunds do not expire under the intended launch terms. Network fees you paid are not part of the refunded commitment.','A transient launch transaction failure is not necessarily a failed campaign: settlement can retry within its permitted launch window. If the campaign fails or its launch deadline expires, use its recorded refund state. Do not assume a pending transaction succeeded or retry with a new payment before checking the receipt.']}
 ]},
 {id:'supply',group:'Using KIDS',title:'Where the supply goes',summary:'Published allocations account for the original supply. Fees are separate from token allocations.',sections:[
  {title:'The allocation',table:{headers:['Purpose','Original supply','Availability'],rows:[['Prelaunch participants','43.5%','Purchased allocation after successful launch'],['Liquidity','43.5%','Paired with accepted SOL'],['Parent A rewards','5%','Eligible snapshot holders'],['Parent B rewards','5%','Eligible snapshot holders'],['Dev at launch','1%','Available to the designated dev at launch'],['Dev vesting','2%','Linear over three calendar months from launch']]}},
  {title:'Dev vesting, in plain numbers',paragraphs:['The dev receives 3% of total supply, not 3% of the participant allocation. One percentage point is available at launch; the remaining two percentage points vest continuously over three calendar months with no cliff. The exact end timestamp depends on the launch date and calendar-month calculation.','For a one-billion-token supply that is 10 million tokens at launch and 20 million vesting. At the midpoint of the vesting interval, half of that 20 million is vested. The claimable amount subtracts anything already claimed. There is no expiration on vested dev entitlement.']},
  {title:'Original supply versus circulating supply',paragraphs:['Allocation percentages use the original supply. Burns may reduce the current token supply without increasing somebody’s original entitlement. Unclaimed reserves are not circulating wallet balances, but scanners may still show them as concentrated holdings.']}
 ]},
 {id:'parents',group:'Using KIDS',title:'Parent rewards',summary:'Two independent 5% reserves. Eligibility comes from the campaign’s snapshot, not today’s balance.',sections:[
  {title:'The 0.05% rule',paragraphs:['To qualify for a parent’s reserve, your wallet must hold at least 0.05% of that parent’s recorded supply at its campaign snapshot. For a one-billion-token parent supply, the threshold is 500,000 tokens. Each parent is checked independently; you can qualify for one or both.','Buying after the snapshot does not create an allocation. Holding some tokens below the threshold is different from holding none. Custodial or exchange holdings may not produce an entitlement for your personal wallet; check how the campaign attributes snapshot ownership.']},
  {title:'How much do I receive?',paragraphs:['Each eligible holder receives a proportional share of that parent’s 5% reserve, based on their qualifying snapshot balance divided by the total eligible balance for that parent. The threshold establishes eligibility; it is not an equal reward per wallet.','The snapshot publisher’s data and exclusions matter. A Merkle proof demonstrates that an allocation is included in a published root; it does not independently prove that the publisher collected every historical balance correctly.']},
  {title:'The claim window',paragraphs:['The new separated-vault policy gives free parent rewards a 30-day claim window starting at successful on-chain launch. At the expiry timestamp, remaining unclaimed tokens in that parent’s vault can be burned; they cannot be taken by the dev or reassigned under that policy.','This policy must be activated for the specific campaign. Earlier campaigns can use different custody. Check the displayed distribution program and exact UTC deadline; do not infer a deadline from this guide. Purchased allocations and SOL refunds are not subject to this free-reward expiry.']},
  {title:'Claim from your eligible wallet',steps:['Connect the wallet whose balance was recorded at the snapshot.','Open the coin’s Claims area and choose Parent rewards.','Check the parent, allocation, already-claimed amount and deadline.','Review and sign the claim; keep its transaction signature until confirmed.']}
 ]},
 {id:'claims',group:'Using KIDS',title:'Find and claim what is yours',summary:'Purchased tokens, SOL refunds and free rewards are separate entitlements.',sections:[
  {title:'Choose the right claim',table:{headers:['Claim','Who receives it','Expiry'],rows:[['Prelaunch tokens','The commitment receipt owner','No expiry'],['Excess or failed-launch SOL','The refund recipient recorded by the campaign','No expiry'],['Parent rewards','The eligible snapshot wallet','30 days only for campaigns using the new policy'],['Dev tokens','The designated dev beneficiary','No expiry; vesting limits what is available']]}},
  {title:'A disabled button should explain why',paragraphs:['“Claimed” means the entitlement was paid. “Nothing vested yet” means the dev has no newly vested amount. “Not eligible” means the snapshot rules were not met. “Expired” is relevant only to a time-limited reward. “Unavailable” or a loading error does not prove that your entitlement is zero.','Connect the same wallet used to commit or qualify. If a signature is pending or the page disconnects, check the transaction and refresh balances before trying again. Never share a recovery phrase to resolve a claim.']},
  {title:'Independent access',paragraphs:['A durable claim system needs publicly available program IDs, instructions and any required snapshot proofs, so a website outage does not erase access. Check the campaign’s verification resources for the available claim route. Do not assume an independent claim tool or proof archive exists until it is actually published.']}
 ]},
 {id:'fees',group:'Mechanics',title:'Trading fees and the family loop',summary:'The pool fee, the LP share and the routing of collected earnings are three different numbers.',sections:[
  {title:'Start with the actual pool',paragraphs:['Read the fee on the verified pool configuration. Different deployed pool tiers can have different rates; this guide does not hardcode one rate for every campaign. KIDS uses Raydium CPMM liquidity, where the total trading fee includes portions outside the LP earnings collected by KIDS.','A pool trading fee is not a token transfer tax. Network fees, slippage and price impact are additional considerations when you trade.']},
  {title:'Collected SOL-side earnings',paragraphs:['The inspected fee-routing source assigns collected SOL earnings in weights of 98 : 20 : 25 : 25, out of 168: KIDS treasury, dev, parent A buyback budget, parent B buyback budget. That is approximately 58.33%, 11.90%, 14.88% and 14.88% of those collected earnings.','These are not percentages of every trade’s volume. For example, 1.68 SOL of collected SOL-side earnings would allocate 0.98 SOL to KIDS, 0.20 SOL to the dev and 0.25 SOL to each parent budget, before integer rounding. Child-token fees follow the separate burn policy, so the SOL distribution must not be advertised as a fixed percentage of all trading volume. Verify the deployed configuration before treating these source rules as live economics.']},
  {title:'Buybacks and burns',paragraphs:['The intended current policy burns the collected child-token fees rather than selling them. Parent budgets buy the specified parent token and burn the tokens received. A budget being allocated or queued is not the same as a completed buyback or burn.','Use the transaction history to distinguish collected, paid, queued, spent and burned amounts. Parent tokens can use different decimal precision; raw integer units are not whole coins. Fee activity requires trades and keeper execution and can be delayed. Burns reduce supply but do not guarantee price appreciation.']},
  {title:'Slippage is your trade limit',paragraphs:['Slippage tolerance limits how much worse the execution may be than the quoted output. Check and change it before signing. A 10% tolerance allows a materially worse fill than 1%; it is not a promise that a trade will cost exactly 10% extra. The transaction’s minimum output, not just a label, must enforce your chosen limit.']}
 ]},
 {id:'security',group:'Mechanics',title:'Liquidity, authorities and trust',summary:'Know what each check proves, and what it does not.',sections:[
  {title:'Locked liquidity',paragraphs:['The launch design creates a Raydium CPMM pool and permanently locks its issued LP position using Burn & Earn, retaining fee-collection rights. Locking LP principal and retaining the right to collect earned fees are compatible. Check the pool, lock account, locked amount and Fee Key custody for the actual coin.','A liquidity lock does not stop normal traders from selling, guarantee a minimum price or guarantee that liquidity has a particular dollar value. It also does not make every external protocol dependency immutable.']},
  {title:'Mint and freeze authorities',paragraphs:['A revoked mint authority means that authority can no longer mint extra tokens for that mint. A revoked freeze authority means that authority can no longer freeze token accounts. Check both fields on chain rather than relying on a logo or badge.','Revoking token authorities does not remove an upgrade authority from the launch or distribution program. These are separate checks. A program-derived vault has no ordinary private key, but an upgradeable program may still be changed by its upgrade authority.']},
  {title:'Purpose-specific claim vaults',paragraphs:['The new distribution design separates paid participant tokens, parent A rewards, parent B rewards and dev vesting into distinct vaults. Fixed terms and an immutable distribution program are the intended protections. Separation alone is not enough if the controlling program remains upgradeable.','For an existing campaign, confirm which distribution version is activated and whether its upgrade authority has actually been revoked. Do not apply a new policy or an “immutable” label retroactively to an older custody arrangement.']},
  {title:'Permissionless market limits',paragraphs:['Do not assume KIDS can block particular wallets from trading a classic token on a permissionless external pool. A website restriction, a launch eligibility rule and a token-level transfer restriction are different mechanisms. No such universal trading ban is promised here.','Smart-contract defects, snapshot errors, compromised keys, third-party protocol risks, market manipulation and service outages remain possible. Published source and passing tests are useful evidence, but neither is an independent audit.']}
 ]},
 {id:'verify',group:'Transparency',title:'Verify the launch',summary:'Check the specific campaign, not a screenshot or an address copied from a stranger.',sections:[
  {title:'Your verification checklist',steps:['Confirm the network and canonical coin mint on the coin page.','Inspect the launch and distribution program IDs, campaign escrow and pool address.','Check mint and freeze authorities, pool fee configuration and LP lock records.','Check claim vaults, their controlling program’s upgrade authority, parent roots, deadlines and dev beneficiary.','Compare a published release and build verification with the deployed program; source availability alone is not bytecode verification.']},
  {title:'What this guide can verify',paragraphs:['This guide explains the intended terms and inspected implementation. It is not a live program registry, independent security audit or certificate that every current campaign uses the newest distribution design. Deployment IDs, binary verification, public proof availability and independent review must be established per campaign.','When a verification resource is missing, treat it as pending. Do not substitute a test program ID, a stale registry or an inaccessible repository for current public evidence.']},
  {title:'Source availability and reuse',paragraphs:['KIDS-owned code uses the PolyForm Noncommercial License 1.0.0 with required notices. This is source-available software, not OSI open source. Commercial use outside the license requires separate permission; attribution alone does not grant it.','Dependencies and third-party materials retain their own licenses. Mascots, logos, video and community icons are not automatically licensed by the software license.'],external:[['Read the PolyForm Noncommercial terms','https://polyformproject.org/licenses/noncommercial/1.0.0/']]}
 ]},
 {id:'faq',group:'Transparency',title:'Questions, answered',summary:'The details that are easy to confuse.',sections:[
  {title:'Is KIDS the same token as Shartcoin?',paragraphs:['No. KIDS is the platform and brand. Shartcoin is a coin launched through it. This guide does not announce a KIDS token sale, date or entitlement.']},
  {title:'Does committing earlier give more tokens?',paragraphs:['Not at a better rate within the same successful campaign. Acceptance is proportional to SOL committed. The final share depends on total commitments and the campaign terms, not queue position.']},
  {title:'Do I need to hold both parents?',paragraphs:['No. Each parent’s eligibility and 5% reserve are independent. Holding both can qualify for both if each threshold was met at its relevant snapshot.']},
  {title:'Can I lose money after a successful launch?',paragraphs:['Yes. A fairer allocation process does not guarantee token value, liquidity depth or resale price. Refund rules cover refundable commitment balances, not losses from trading after launch.']},
  {title:'Are public launches open?',paragraphs:['Use the Launch page for the current opening schedule and availability. A countdown reaching zero does not by itself prove that launch creation is enabled. This guide intentionally does not repeat a date that can become stale.'],links:[['View launch status','@launch']]},
  {title:'What comes next?',paragraphs:['The first focus is the community-parent launch format. Wider public launching and further formats depend on verified contract behavior, operational readiness and the release process. Ideas discussed publicly are not active features or promised token allocations.']}
 ]}
];
export const docText = doc => [doc.title,doc.summary,...doc.sections.flatMap(s=>[s.title,...(s.paragraphs||[]),...(s.steps||[]),...(s.table?.rows.flat()||[])])].join(' ');
export const docHref = id => id.startsWith('@') ? '#'+id.slice(1) : '#docs/'+id;
