import {ParentIcon} from './Parents';
import {CoinPfp} from './CoinPfp';
import {ArrowRight,ArrowDown,Users} from '@phosphor-icons/react';
export function Home({open,go}) {
  return <section className="clear-home">
    <div className="clear-hero"><div><h1>Two communities.<br className="compact-break"/> One kid.</h1><p>Fartcoin × Buttcoin. Meet their kid, $Shartcoin.</p><div className="hero-actions"><button className="primary" onClick={()=>open('shart')}>Explore Shartcoin <ArrowRight size={26}/></button><button className="text-button" onClick={()=>document.getElementById('what-happens-next').scrollIntoView({behavior:'smooth'})}>How it works</button></div></div><div className="hero-family" aria-label="Fartcoin and Buttcoin are the parent communities of Shartcoin"><div className="hero-parents"><div><ParentIcon name="Fartcoin"/><strong>Fartcoin</strong></div><span aria-hidden="true">+</span><div><ParentIcon name="Buttcoin"/><strong>Buttcoin</strong></div></div><div className="hero-family-link" aria-hidden="true"><ArrowDown size={28}/></div><button className="hero-child" onClick={()=>open('shart')} aria-label="Explore Shartcoin, the child coin"><CoinPfp className="hero-child-pfp" alt="" size={68}/><span><small>THEIR KID</small><strong>Shartcoin</strong><span>$Shartcoin</span></span><ArrowRight size={24}/></button></div></div>
    <div className="first-kid"><div className="section-intro"><div><h2>The first kid</h2><p>Public launches closed.</p></div><span>Two parent communities.<br/>One coin.</span></div><div className="coin-row"><div className="coin-identity"><img className="coin-logo" src="/assets/shart-pfp.png" alt="Shartcoin"/><div><strong>Shartcoin</strong><span>$Shartcoin</span></div><span className="prelaunch">Prelaunch</span></div><div className="coin-fact"><span>Parents</span><strong className="inline-parent-pair"><ParentIcon name="Fartcoin"/> Fartcoin <span>×</span><ParentIcon name="Buttcoin"/> Buttcoin</strong></div><div className="coin-fact"><span>Parent allocation</span><strong>10% proposed · Not funded</strong></div><button className="outlined" onClick={()=>open('shart')}>View coin <ArrowRight size={24}/></button></div></div>
    <div className="home-explanation"><section className="home-family"><h2>A coin with a family</h2><p>Two parent communities. One little menace.</p><div className="family-parent-row"><div><ParentIcon name="Fartcoin"/><span>Parent 01<strong>Fartcoin</strong></span></div><div><ParentIcon name="Buttcoin"/><span>Parent 02<strong>Buttcoin</strong></span></div></div><div className="family-child"><ArrowDown size={28}/><CoinPfp className="family-child-pfp" alt="" size={68}/><strong>Shartcoin</strong><span>$Shartcoin</span></div></section>
    <section className="home-roadmap" id="what-happens-next"><h2>What happens next</h2><p>From parents to a coin. Here’s the roadmap.</p><ol>{[['Confirm parents','Verify the exact Fartcoin and Buttcoin mints.'],['Prelaunch','Commit SOL for a proportional allocation.'],['Launch & refunds','The capped pool opens; excess SOL is refunded.'],['Allocations','Eligible parent holders can claim once the reserve is funded.']].map(([title,description],i)=><li key={title}><span>{i+1}</span><strong>{title}</strong><p>{description}</p></li>)}</ol></section></div>
    <div className="after-genesis"><div><Users size={28}/><p><strong>Two parents. Your next kid.</strong><span>Public launches are coming.</span></p></div><button className="text-button" onClick={()=>go('Launch')}>Launch <ArrowRight size={19}/></button></div>
    <p className="home-launch-note">$Shartcoin is prelaunch. Parent mints are unverified. No contract or trading yet.</p>
  </section>;
}
