import {useEffect,useState} from 'react';
async function request(csrf){const response=await fetch('/api/admin/launch-test',{method:csrf?'POST':'GET',headers:csrf?{'Content-Type':'application/json','X-Kids-CSRF':csrf}:{},body:csrf?'{}':undefined,signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Launch test unavailable');return data;}
export function LaunchRehearsal({csrf}){
 const [state,setState]=useState(null),[error,setError]=useState(''),[starting,setStarting]=useState(false);
 const running=state?.job?.status==='running';
 useEffect(()=>{let active=true;const refresh=()=>request().then(next=>{if(active)setState(next);}).catch(e=>{if(active)setError(e.message);});refresh();const timer=running?setInterval(refresh,2000):null;return()=>{active=false;if(timer)clearInterval(timer);};},[running]);
 async function start(){setStarting(true);setError('');try{setState(await request(csrf));}catch(e){setError(e.message);}finally{setStarting(false);}}
 const report=state?.report;
 return <section className="launch-test" aria-labelledby="launch-test-title"><div className="admin-heading"><div><h2 id="launch-test-title">Local launch test</h2><p>Launch → claims → fees → parent burns</p></div><button className="primary" disabled={running||starting} onClick={start}>{running?'Testing launch…':starting?'Starting…':'Run local launch test'}</button></div>
 <p className="small muted">Creates a separate test coin using local wallets: 4 SOL committed, 3 SOL accepted, 1 SOL refunded. No changes to the active Shartcoin campaign.</p>
 {error&&<p role="alert">{error}</p>}{state?.job&&<p role="status">{running?(state.job.stage==='fees-and-parent-burns'?'Collecting fees and testing parent buybacks and burns…':'Launching, refunding and testing token claims…'):state.job.status==='passed'?'Launch test passed.':state.job.error}</p>}
 {report&&<><div className="launch-test-totals"><p><strong>{Number(report.committedLamports)/1e9} SOL</strong> committed</p><p><strong>{Number(report.acceptedLamports)/1e9} SOL</strong> in pool</p><p><strong>{Number(report.refundedLamports)/1e9} SOL</strong> refunded</p></div>{report.claims&&<p>Participant and parent claims verified · Dev vesting starts at pool launch</p>}{report.fees&&<div className="launch-fee-results"><h3>Fee routing & parent burns verified</h3><div className="launch-test-totals"><p><strong>{(Number(report.fees.state.treasuryPaid)/1e9).toLocaleString(undefined,{maximumFractionDigits:6})} SOL</strong>KIDS treasury</p><p><strong>{(Number(report.fees.state.devPaid)/1e9).toLocaleString(undefined,{maximumFractionDigits:6})} SOL</strong>Dev fees</p><p><strong>{(Number(report.fees.state.parentASpent)/1e9).toLocaleString(undefined,{maximumFractionDigits:6})} SOL</strong>Spent per parent</p></div><p>{report.fees.burns.map(b=>`Parent ${b.parent+1}: ${(Number(b.burnedRaw)/1e6).toLocaleString(undefined,{maximumFractionDigits:4})} tokens burned`).join(' · ')}</p></div>}<details><summary>Last successful test · addresses and checks</summary><p>Recorded qualification result, not a live balance.</p>{['programId','campaign','pool','mint','feeNft','signature'].map(field=><label key={field}>{({programId:'Program',feeNft:'Fee Key NFT'})[field]||field}<input readOnly value={report[field]}/></label>)}<ul>{[...report.checks,...(report.fees?.checks||[])].map(check=><li key={check}>{check}</li>)}</ul><p>{[...report.limitations,...(report.fees?.limitations||[])].join('. ')}.</p></details></>}
 </section>;
}
