import {netLabel,explorerTx} from './network-label.mjs';
import {walletForOwner} from './wallet-connection.mjs';
import {friendlyError} from './friendly-errors.mjs';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowsDownUp,ChartLine,CheckCircle,Copy,Globe,LockKey,Play,XLogo} from '@phosphor-icons/react';
import {accountApi} from './Account';
import {ParentIcon} from './Parents';
import {CoinUpdates} from './CoinUpdates';
import {resolveShartVideo} from './coin-media';
import {resolveCoinDescription} from './coin-display';
import './post-launch.css';
import {LocalTradePanel} from './LocalTradePanel';
const formatWhole=(value,decimals=6)=>value==null?'—':Math.round(Number(value)/10**decimals).toLocaleString('en-GB');
const format=(value,decimals=6)=>value==null?'—':(Number(value)/10**decimals).toLocaleString('en-GB',{maximumFractionDigits:decimals===9?4:2});
function moveTab(event){const tabs=[...event.currentTarget.querySelectorAll('[role="tab"]')],index=tabs.indexOf(event.target);if(index<0)return;let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;else if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=tabs.length-1;else return;event.preventDefault();tabs[next].focus();tabs[next].click();}
const short=value=>value?`${value.slice(0,5)}…${value.slice(-5)}`:'Not connected';
const PARENT_NAMES=['Fartcoin','Buttcoin'];
const shortSig=v=>v?v.slice(0,6)+'…'+v.slice(-6):'';
function Flywheel({data,verified}){
 const [copied,setCopied]=useState('');const f=verified?data.fees:null,events=(verified&&data.feeEvents)||[];
 const burns=events.filter(e=>e.kind==='buy-burn');
 const copy=async v=>{try{await navigator.clipboard.writeText(v);setCopied(v);setTimeout(()=>setCopied(''),1500);}catch{}};
 return <section className="post-flywheel"><div className="post-flywheel-head"><div><h2>Every trade feeds the family.</h2><p>The 2% pool fee is collected, turned into SOL and split by the program: KIDS treasury, the dev, and buybacks of both parents that are burned for good.</p></div><span className="post-preview-badge">{f?format(f.totalSol,9)+' SOL collected':'No fees yet'}</span></div>
  <div className="post-flywheel-grid">
   <div className="post-flywheel-tile"><span>KIDS treasury</span><strong>{f?format(f.treasuryPaid,9):'—'} <small>SOL</small></strong></div>
   <div className="post-flywheel-tile"><span>Dev</span><strong>{f?format(f.devPaid,9):'—'} <small>SOL</small></strong></div>
   {PARENT_NAMES.map((name,i)=><div key={name} className="post-flywheel-tile is-burn"><span><ParentIcon name={name}/> {name} buyback</span><strong>{f?format(i?f.parentBSpent:f.parentASpent,9):'—'} <small>SOL</small></strong><em>🔥 {f?format(i?f.parentBBurned:f.parentABurned,0):'—'} burned</em>{f&&BigInt(i?f.parentBAllocated:f.parentAAllocated)>BigInt(i?f.parentBSpent:f.parentASpent)&&<small>{format(BigInt(i?f.parentBAllocated:f.parentAAllocated)-BigInt(i?f.parentBSpent:f.parentASpent),9)} SOL queued</small>}</div>)}
  </div>
  <div className="post-burn-log"><div className="post-burn-log-head"><strong>Latest buybacks and burns</strong><span>{burns.length?burns.length+' on record':'None yet'}</span></div>
   {burns.length===0?<p>The first buyback runs after the first fees are collected.</p>:<ul>{burns.slice(0,8).map(e=><li key={e.id}><span className="post-burn-when">{new Date(e.at*1000).toLocaleString()}</span><span className="post-burn-what"><ParentIcon name={PARENT_NAMES[e.index]||'Parent'}/> {PARENT_NAMES[e.index]||'Parent'}: {format(e.amount,9)} SOL → 🔥 {format(e.delta?.[e.index?'parentBBurned':'parentABurned'],0)} burned</span><span className="post-burn-sig">{data.explorerUrl?<a href={explorerTx(data,e.signature)} target="_blank" rel="noreferrer">{shortSig(e.signature)}</a>:<code title={e.signature}>{shortSig(e.signature)}</code>}<button type="button" onClick={()=>copy(e.signature)}>{copied===e.signature?'Copied':'Copy'}</button></span></li>)}</ul>}
   <small>{data?.explorerUrl?'Signatures open on the explorer.':'Private test ledger: signatures are real on this ledger but not on public explorers.'}</small>
  </div>
 </section>;
}
function Metric({label,value,note}){return <div className="post-metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>;}
function ClaimCard({label,value,unit,note,onClaim,enabled,busy,reason}){return <article className={'post-claim-card'+(reason==='Claimed'?' is-claimed':'')}><span>{label}</span><strong>{value}<small>{unit}</small></strong><div><p>{note}</p><button className="outlined" disabled={!enabled||busy} onClick={onClaim}>{busy?'Confirming…':enabled?'Claim':reason||'Nothing to claim'}</button></div></article>;}
export function PostLaunch({identity,onSignIn,profile,posts=[],go,preview=false}){
 const [tab,setTab]=useState('Market'),[claimTab,setClaimTab]=useState('Your allocation'),[side,setSide]=useState('Buy'),[amount,setAmount]=useState(''),[snapshot,setSnapshot]=useState(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[copied,setCopied]=useState(''),[videoError,setVideoError]=useState(false);
 const [claimBusy,setClaimBusy]=useState(''),[claimResult,setClaimResult]=useState('');
 const owner=identity?.owner,ownerRef=useRef(owner),claimLock=useRef(false),claimPending=useRef(null);ownerRef.current=owner;
 useEffect(()=>{setClaimResult('');claimPending.current=null;},[owner]);
 async function claim(action){if(claimLock.current||!canClaim(action.startsWith('parent')?'parent':action,action==='parentB'?1:0))return;claimLock.current=true;setClaimBusy(action);setClaimResult('');try{const session=await accountApi('state');if(session.owner!==owner||ownerRef.current!==owner)throw Error('Wallet changed. Refresh your allocations.');let result;
 if(claims?.localClaimEnabled){result=await accountApi('postlaunch/claim',{action,campaign:claims.campaign},session.csrf);}
 else{
  const key=JSON.stringify([owner,claims.campaign,action]);if(claimPending.current?.key!==key)claimPending.current={key,requestId:crypto.randomUUID()};const pending=claimPending.current;
  const intent=await accountApi('postlaunch/claim/prepare',{action,campaign:claims.campaign,requestId:pending.requestId},session.csrf);
  if(ownerRef.current!==owner||intent.owner!==owner||intent.campaign!==claims.campaign||intent.programId!==data.programId||intent.mint!==data.mint||intent.genesisHash!==claims.genesisHash)throw Error('Claim identity changed. Refresh before signing.');
  if(!pending.body){
   const provider=await walletForOwner(owner);if(ownerRef.current!==owner)throw Error('Wallet changed. Refresh your allocations.');
   const {decodeApprovedClaim}=await import('./claim-signing.mjs'),{assertApprovedMessage}=await import('./escrow-signing.mjs');
   const tx=decodeApprovedClaim(Uint8Array.from(atob(intent.unsignedTransactionBase64),c=>c.charCodeAt(0)),{owner,programId:intent.programId,campaign:intent.campaign,mint:intent.mint,action}),approved=tx.message.serialize().slice();
   const signed=await provider.signTransaction(tx);if(ownerRef.current!==owner||provider.publicKey?.toString()!==owner)throw Error('Wallet changed before submission.');
   const bytes=assertApprovedMessage(signed,approved);let text='';for(const byte of bytes)text+=String.fromCharCode(byte);pending.body={intentId:intent.intentId,signedTransactionBase64:btoa(text)};
  }
  if(ownerRef.current!==owner)throw Error('Wallet changed before submission.');result=await accountApi('postlaunch/claim/submit',pending.body,session.csrf);
 }
 claimPending.current=null;if(ownerRef.current!==owner)return;if(!result.signature)throw Error('No transaction receipt returned. Refresh to check your claim.');setClaimResult({ok:true,title:'Claim confirmed',detail:'Your coins are in your wallet on the test ledger.',technical:result.signature});setRefresh(n=>n+1);}catch(e){if(ownerRef.current===owner){if(!claimPending.current?.body&&e.message.includes('Unsigned claim expired'))claimPending.current=null;setClaimResult({ok:false,...friendlyError(e,{payWith:'SOL'})});}}finally{claimLock.current=false;setClaimBusy('');}}
 useEffect(()=>{let active=true;setError('');accountApi(preview?'postlaunch-preview':'postlaunch').then(data=>{if(active)setSnapshot({owner,data});}).catch(()=>{if(active){setSnapshot(null);setError('Launch data is not connected.');}});return()=>{active=false;};},[owner,refresh,preview]);
 const data=snapshot&&snapshot.owner===owner?snapshot.data:null;
 const verified=data?.configured===true&&['localnet','devnet','mainnet'].includes(data.network)&&data.scope===(preview?data.network+'-rehearsal':'active-'+data.network)&&typeof data.mint==='string'&&typeof data.pool==='string';
 const claims=verified&&data.claims?.owner===owner?data.claims:null;const net=netLabel(data?.network);
 const remaining=(total,claimed)=>{try{return BigInt(total||0)>BigInt(claimed||0);}catch{return false;}};
 const claimedAll=(total,claimed)=>{try{return BigInt(claimed||0)>0n&&BigInt(claimed||0)>=BigInt(total||0);}catch{return false;}};
 const reasonFor=(kind,index=0)=>{if(!owner)return 'Sign in first';if(!claims)return 'Loading';if(!(claims.localClaimEnabled||claims.externalClaimEnabled))return 'Test wallets only';if(kind==='participant')return claimedAll(claims.participant?.allocatedRaw,claims.participant?.claimedRaw)?'Claimed':BigInt(claims.participant?.allocatedRaw||0)===0n?'No allocation':'';if(kind==='refund')return BigInt(claims.refund?.refundedLamports||0)>0n?'Refunded':'Nothing to refund';if(kind==='dev')return claims.dev?.isDev?'Nothing vested yet':'Dev wallet only';const item=claims.parents?.[index];if(!item)return 'Loading';if(item.eligible===false)return 'Not eligible';return claimedAll(item.allocationRaw,item.claimedRaw)?'Claimed':'';};
 const canClaim=(kind,index=0)=>{if(!owner||!(claims?.localClaimEnabled||claims?.externalClaimEnabled))return false;if(kind==='participant')return remaining(claims.participant?.allocatedRaw,claims.participant?.claimedRaw);if(kind==='refund')return remaining(claims.refund?.claimableLamports,0);if(kind==='dev')return claims.dev?.isDev&&remaining(claims.dev?.claimableRaw,0);const item=claims.parents?.[index];return item?.eligible&&remaining(item.allocationRaw,item.claimedRaw);};
 const video=resolveShartVideo(profile?.video);
 async function copy(value,label){try{await navigator.clipboard.writeText(value);setCopied(`${label} copied`);}catch{setCopied('Copy unavailable. Select the address in Pool details.');}}
 return <section className="post-launch">
  <div className="post-page-bar"><button className="text-button" onClick={()=>go('Shart')}><ArrowLeft size={17}/> Prelaunch page</button><div><span className="post-preview-badge">{preview?'Post-launch preview':'Shartcoin launch'}</span><span>{verified?(preview?net.name+' test pool · Separate from Shartcoin':'Active Shartcoin · '+net.name):preview?'Trading and claims are not connected':'Active campaign has not launched'}</span>{!preview&&!verified&&<button className="text-button" onClick={()=>go('PostLaunchPreview')}>View post-launch preview</button>}</div><button className="text-button" onClick={()=>setRefresh(n=>n+1)}>Refresh</button></div>
  <div className="post-terminal">
   <div className="post-main">
    <div className="post-market-heading"><div><span className="post-kicker">The next chapter</span><h1>Shartcoin <span>$Shartcoin</span></h1></div><span className={`post-status ${verified?'is-verified':''}`}><span/>{verified?'Pool verified '+net.on:'Awaiting pool connection'}</span></div>
    <div className="post-metrics"><Metric label="Pool liquidity" value={verified?`${format(data.quoteReserveLamports,9)} SOL`:'—'} note="SOL side of the pool"/><Metric label="Token reserve" value={verified?formatWhole(data.baseReserveRaw):'—'} note="$Shartcoin in the pool"/><Metric label="24h volume" value="—" note="Market feed not connected"/><Metric label="Trading fee" value="2%" note="Approved pool terms"/></div>
    <section className="post-market-panel" aria-label="Coin market and media"><div className="post-panel-tabs" role="tablist" onKeyDown={moveTab} aria-label="Coin content">{['Market','Dev updates',...(video?['Video']:[])].map(name=><button id={`post-tab-${name.replaceAll(' ','-')}`} key={name} role="tab" tabIndex={tab===name?0:-1} aria-selected={tab===name} aria-controls="post-content-panel" onClick={()=>setTab(name)}>{name==='Market'?<ChartLine size={17}/>:name==='Video'?<Play size={17}/>:null}{name}</button>)}</div>
     <div id="post-content-panel" role="tabpanel" aria-labelledby={`post-tab-${tab.replaceAll(' ','-')}`} className={`post-panel-content ${tab==='Video'?'is-video':''}`}>
      {tab==='Market'&&<div className="post-chart-empty"><div className="post-chart-grid" aria-hidden="true"/><div className="post-chart-message"><ChartLine size={35} weight="light"/><h2>A home for every move.</h2><p>The price chart appears here when the market feed is connected.</p><span>{verified?'Pool confirmed. Price history is not available yet.':'Connect a market feed to see trading activity.'}</span></div><div className="post-market-legend"><span><i/> $Shartcoin / SOL</span><span>Raydium CPMM</span></div></div>}
      {tab==='Dev updates'&&<CoinUpdates profile={profile} posts={posts} ready={false} admin={false}/>}
      {tab==='Video'&&(videoError?<div className="post-media-error"><p>Video unavailable.</p><button className="outlined" onClick={()=>setVideoError(false)}>Retry video</button></div>:<video key={video} controls playsInline preload="metadata" src={video} aria-label="Shartcoin introduction" onError={()=>setVideoError(true)}/>)}
     </div>
    </section>
    <div className="post-pool-strip"><span><LockKey size={17}/>{verified&&data.liquidityLocked?'LP locked · '+net.name+' verified':verified&&data.liquidityLockQualified?(preview?'LP lock verified in launch test':'LP lock verified at launch'):'LP lock verification pending'}</span><span><CheckCircle size={17}/>{verified&&data.mintAuthorityRevoked&&data.freezeAuthorityRevoked?'Mint & freeze revoked':'Mint & freeze revocation required'}</span><details><summary>Pool details</summary><dl><dt>Network</dt><dd>{preview?'Localnet rehearsal':'Active localnet campaign'}</dd><dt>Pool</dt><dd>{verified?data.pool:'Not connected'}</dd><dt>Mint</dt><dd>{verified?data.mint:'Not connected'}</dd><dt>Launch transaction</dt><dd>{verified?(data.launchSignature||'Not recorded'):'Not connected'}{verified&&data.receiptHistoryAvailable===false&&<small>Receipt history unavailable; pool state verified on chain.</small>}</dd><dt>Fee routing</dt><dd>{data?.fees?`${format(data.fees.treasuryPaid,9)} SOL to KIDS · ${format(data.fees.devPaid,9)} SOL to dev`:'Not initialized for this pool'}</dd>{data?.fees&&<><dt>Parent buybacks</dt><dd>{format(data.fees.parentASpent,9)} SOL / {format(data.fees.parentBSpent,9)} SOL spent</dd></>}</dl></details></div>
    <Flywheel data={data} verified={verified}/>
    <section className="post-claims" aria-busy={!!claimBusy}><div className="post-claims-heading"><h2>Your piece of the family.</h2>{owner?<span>{short(owner)}</span>:<button className="text-button" onClick={onSignIn}>Sign in to check allocations <ArrowRight size={16}/></button>}</div>{claimResult&&<div className={'trade-feedback '+(claimResult.ok?'is-ok':'is-problem')} role="status"><strong>{claimResult.title}</strong>{claimResult.detail&&<p>{claimResult.detail}</p>}{claimResult.technical&&<details><summary>{claimResult.ok?'Transaction signature':'Technical details'}</summary><code>{claimResult.technical}</code></details>}</div>}{verified&&owner&&!claims&&<p className="post-claim-feedback">Wallet allocations are unavailable. Refresh to retry.</p>}{claims&&!claims.localClaimEnabled&&!claims.externalClaimEnabled&&<p className="post-claim-feedback">Claims are available to local test wallets only in this rehearsal.</p>}<div className="post-claim-tabs" role="tablist" onKeyDown={moveTab} aria-label="Allocation category">{['Your allocation','Parent rewards','Dev vesting'].map(name=><button role="tab" id={`claim-tab-${name.replaceAll(' ','-')}`} aria-controls="claim-content-panel" tabIndex={claimTab===name?0:-1} key={name} aria-selected={claimTab===name} onClick={()=>setClaimTab(name)}>{name}</button>)}</div>
     <div id="claim-content-panel" className="post-claim-content" role="tabpanel" aria-labelledby={`claim-tab-${claimTab.replaceAll(' ','-')}`}>
      {claimTab==='Your allocation'&&<div className="post-claim-grid"><ClaimCard onClaim={()=>claim('participant')} enabled={canClaim('participant')} busy={!!claimBusy} reason={reasonFor('participant')} label="Prelaunch tokens" value={format(claims?.participant?.allocatedRaw)} unit="$Shartcoin" note={claims?.participant?(claimedAll(claims.participant.allocatedRaw,claims.participant.claimedRaw)?'All claimed: these coins are in your wallet.':`${format(claims.participant.claimedRaw)} already claimed`):'Your proportional allocation appears after wallet verification.'}/><ClaimCard onClaim={()=>claim('refund')} enabled={canClaim('refund')} busy={!!claimBusy} reason={reasonFor('refund')} label="Excess commitment" value={format(claims?.refund?.claimableLamports,9)} unit="SOL" note={claims?.refund?`${format(claims.refund.refundedLamports,9)} SOL returned`:'Unclaimed refunds stay separate from your token allocation.'}/></div>}
      {claimTab==='Parent rewards'&&<><div className="post-parent-claims">{['Fartcoin','Buttcoin'].map((name,index)=><article key={name}><div><ParentIcon name={name}/><strong>{name} holders</strong><span>5% reserve</span></div><p>Held ≥0.05% at the snapshot</p><strong>{format(claims?.parents?.[index]?.allocationRaw)} <small>$Shartcoin</small></strong><span>{claims?.parents?.[index]?.eligible===false?'This wallet held no '+name+' at the snapshot':claims?.parents?.[index]?.eligible===true?'Eligible: held '+name+' at the snapshot':'Snapshot lookup not connected'}</span><button className="outlined" disabled={!!claimBusy||!canClaim('parent',index)} onClick={()=>claim(index===0?'parentA':'parentB')}>{claimBusy?'Confirming…':canClaim('parent',index)?'Claim':reasonFor('parent',index)||'Nothing to claim'}</button></article>)}</div><p className="post-claim-footnote">Either parent qualifies independently. You do not need to hold both.</p></>}
      {claimTab==='Dev vesting'&&<div className="post-dev-claim"><div><span>Dev allocation · 3%</span><h3>1% at launch. 2% over 3 months.</h3><p>Linear vesting from launch, with no cliff.</p></div><div><span>Available now</span><strong>{format(claims?.dev?.claimableRaw)} <small>$Shartcoin</small></strong><button className="outlined" disabled={!!claimBusy||!canClaim('dev')} onClick={()=>claim('dev')}>{claimBusy?'Confirming…':canClaim('dev')?'Claim vested tokens':reasonFor('dev')}</button></div></div>}
     </div>
    </section>
   </div>
   <aside className="post-rail">
    <div className="post-banner">{profile?.banner?<img src={profile.banner} alt="Shartcoin banner"/>:<><span>FARTCOIN × BUTTCOIN</span><strong>Oh, Shartcoin.</strong></>}<div className="post-socials">{[{key:'xUrl',label:'Shartcoin on X',Icon:XLogo},{key:'websiteUrl',label:'Shartcoin website',Icon:Globe}].map(({key,label,Icon})=>profile?.[key]?<a key={key} href={profile[key]} target="_blank" rel="noopener noreferrer" aria-label={label}><Icon size={18}/></a>:<button key={key} disabled aria-label={`${label} unavailable`}><Icon size={18}/></button>)}</div></div>
    <div className="post-identity">{profile?.logo?<img src={profile.logo} alt="Shartcoin logo"/>:<span className="shart-mark" aria-hidden="true">S!</span>}<div><div className="post-inline-parents"><ParentIcon name="Fartcoin"/><span>Fartcoin</span><b>×</b><ParentIcon name="Buttcoin"/><span>Buttcoin</span></div><strong>Shartcoin</strong><small>$Shartcoin</small></div></div>
    <p className="post-description">{resolveCoinDescription(profile?.description)}</p>
    <button className="post-contract" disabled={!verified} onClick={()=>copy(data.mint,'Mint address')}><span>CA</span><code>{verified?short(data.mint):'Available after connection'}</code><Copy size={16}/></button>
    <LocalTradePanel owner={owner} campaign={data?.campaign} wallet={data?.wallet||null} network={data?.network||'localnet'} enabled={verified&&!!owner} localExecution={claims?.localClaimEnabled===true} mint={data?.mint} pool={data?.pool} programId={data?.programId} genesisHash={data?.genesisHash} onSignIn={onSignIn} onTraded={()=>setRefresh(n=>n+1)}/>
    <div className="post-life"><strong>Two parents. One kid.</strong><p>Fartcoin + Buttcoin → Shartcoin</p></div>
   </aside>
  </div>
  <span className="post-announcement" role="status" aria-live="polite">{copied||error}</span>
 </section>;
}
