import {resolveCoinDescription} from './coin-display';
import {resolveShartVideo} from './coin-media';
import {LocalCommitPanel,usePrelaunchChain,LegacyEscrow} from './LocalPrelaunch';
import {LaunchStatus,OpensIn} from './LaunchStatus';import {formatUtc} from './launch-status';
import {CoinSkeleton} from './CoinSkeleton';
import {netLabel} from './network-label.mjs';
import {chainAllocation} from './prelaunch-chain';
import {DevVesting} from './DevVesting';
import {ParentIcon} from './Parents';
import {CoinUpdates} from './CoinUpdates';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,XLogo,Globe} from '@phosphor-icons/react';
import {PRELAUNCH,allocation,parseSol,sol,emptyPrelaunch} from './prelaunch.js';
export function Prelaunch({identity,onSignIn,state=emptyPrelaunch,service,onRefresh,profile,posts=[],onAction,ready,go}){
 const [amount,setAmount]=useState('1'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [videoError,setVideoError]=useState(false);
 const featuredVideo=resolveShartVideo(profile?.video);
 const chain=usePrelaunchChain(identity?.owner||null),live=chain.data?.configured===true,preview=chain.data?.configured===false,net=netLabel(chain.data?.network);
 const loading=!chain.data&&!chain.error;
 const nextTerms=chain.data?.next?.terms,policy=live?{cap:BigInt(chain.data.hardCapLamports),softCap:BigInt(chain.data.softCapLamports),poolUsd:chain.data.poolHardUsd,softPoolUsd:chain.data.poolSoftUsd}:nextTerms?{cap:BigInt(nextTerms.hard),softCap:BigInt(nextTerms.soft),poolUsd:Number(BigInt(nextTerms.hard))/1e9*400,softPoolUsd:Number(BigInt(nextTerms.soft))/1e9*400}:PRELAUNCH;
 const committed=live?BigInt(state.committed):0n,current=live?chainAllocation(chain.data):{total:0n,retained:0n,refund:0n};
 const fundingPhase=live?chain.data.phase:state.phase;
 const funded=Number(current.total)/Number(policy.cap),softMarker=Number(policy.softCap)*100/Number(policy.cap),acceptedTotal=live&&fundingPhase==='failed'?0n:current.total>policy.cap?policy.cap:current.total,excessTotal=current.total-acceptedTotal;
 let estimate;try{estimate=allocation(committed+parseSol(amount));}catch{}
 async function act(action,payload={}){if(busy)return;setBusy(true);setError('');setMessage('');try{await onAction(action,payload);if(action==='prelaunch-commit')setAmount('');setMessage(action==='prelaunch-reset'?"reset. No real funds were involved.":action==='prelaunch-commit'?"commitment saved. No SOL was transferred.":action==='prelaunch-refund'?"refund marked as claimed. No SOL was transferred.":"launch outcome calculated. No token or pool was created.");}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="prelaunch-page sidebar-campaign">
  {chain.data?.phase==='launched'&&<div className="prelaunch-preview-link"><button className="text-button" onClick={()=>go('PostLaunch')}>View launched coin <ArrowRight size={15}/></button></div>}


  {!ready&&<p className="small muted" role="status">{service} <button className="text-button" onClick={onRefresh}>Retry connection</button></p>}
  <div className={`campaign-overview ${featuredVideo?'with-intro-video':''}`}> {live&&<LaunchStatus data={chain.data} go={go} onRefresh={chain.refresh}/>}{featuredVideo&&<aside className="dev-video-card top-dev-video" aria-label="Featured dev video"><div className="dev-video-heading"><strong>Meet Shartcoin</strong><span>From the dev</span></div>{videoError?<div className="dev-video-failure">Video unavailable<button onClick={()=>setVideoError(false)}>Retry</button></div>:<video key={featuredVideo} controls playsInline preload="metadata" src={featuredVideo} aria-label="Shartcoin featured dev video" onError={()=>setVideoError(true)}/>}<div className="video-intro-copy"><strong>Meet Shartcoin.</strong><p>{resolveCoinDescription(profile?.description)?.trim()||'Fartcoin × Buttcoin. Two communities. One unfortunate combination.'}</p></div></aside>}<section className={`funding-visual ${featuredVideo?'has-featured-video':''}`} aria-label="Prelaunch funding progress" aria-busy={loading}>
   {loading?<CoinSkeleton variant="funding"/>:<>
   <div className="funding-meter"><div className="funding-title"><span><strong>Shartcoin prelaunch</strong></span><div className="funding-badges"><span>{live?net.name+' escrow':chain.error?'Unavailable':preview?'Not open yet':'Connecting…'}</span></div></div><div className="funding-headline"><div><span className="funding-label">Total committed</span><h2>{live||preview?Number(sol(current.total)).toLocaleString('en-GB',{maximumFractionDigits:current.total<1000000000n?6:2}):'—'}<small> SOL</small></h2></div><div className="subscription-pill"><strong>{live||preview?funded.toFixed(2)+'×':'—'}</strong><span>of hard cap</span></div></div>
   <div className="funding-cap-labels"><span><small>Soft cap</small><b>{Number(sol(policy.softCap)).toLocaleString('en-GB',{maximumFractionDigits:2})} SOL</b></span><span><small>Hard cap</small><b>{Number(sol(policy.cap)).toLocaleString('en-GB',{maximumFractionDigits:2})} SOL</b></span></div>
   <div className="raise-meter" role="img" aria-label={`Pool funding is ${Math.min(100,funded*100).toFixed(0)} percent of hard cap; ${sol(policy.softCap)} SOL soft cap; ${sol(policy.cap)} SOL hard cap; ${sol(excessTotal)} SOL refundable excess`}><div style={{width:`${Math.min(100,Number(acceptedTotal)*100/Number(policy.cap))}%`}}/><span className="soft-cap-marker" style={{left:`${softMarker}%`}}/><span className="hard-cap-marker" style={{left:'100%'}}/></div>
   <div className="funding-split-labels"><div><span><i/>{live&&fundingPhase==='open'?'Pool estimate':'Into pool'}</span><strong>{sol(acceptedTotal)} <small>SOL</small></strong></div><div><span><i/>To refund</span><strong>{Number(sol(excessTotal)).toLocaleString('en-GB',{maximumFractionDigits:2})} <small>SOL</small></strong></div></div>
   <p className="allocation-note">{live&&fundingPhase==='failed'?'Launch requirements not met · full SOL refunds.':'Pro-rata allocation · excess SOL refunded.'}</p>{chain.error&&<p className="small warning" role="alert">Escrow unavailable. <button className="text-button" onClick={chain.refresh}>Retry</button></p>}</div>
  <div className="launch-stages" aria-label="Launch stages"><span className={fundingPhase==='open'?'current':''}><b>1</b> Commit</span><i/><span className={['settled','awaiting-launch','launched','failed'].includes(fundingPhase)?'current':''}><b>2</b> Allocate</span><i/><span className={['settled','launched','failed'].includes(fundingPhase)?'current':''}><b>3</b> Launch & refund</span><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setMessage('Preview link copied.');}catch{setError('Copy the page address from your browser.');}}}>Share ↗</button></div>
  </>}
  </section></div>
  <div className="prelaunch-layout"><div>
   <section className="community-claims" aria-label="Parent community allocations"><div className="claims-heading"><h2>Parent holder rewards</h2><span>10% Shartcoin reserve · {live&&chain.data.version===3?'Allocated '+net.on:'Not allocated yet'}</span></div><div className="community-claim-grid">{['Fartcoin','Buttcoin'].map(name=><article key={name}><div className="community-claim-title"><ParentIcon name={name}/><strong>{name} holders</strong><b>5%</b></div><div className="community-share" role="img" aria-label={`${name}: half of the parent reserve`}><span className={name==='Fartcoin'?'first-parent':'second-parent'}/></div><p className="claim-eligibility">Hold ≥0.05% of {name} supply at snapshot</p><div className="claim-value"><span>Your Shartcoin</span><strong>{live&&chain.data.version===3?'Claims open at launch':'Awaiting snapshot'}</strong></div><button className="outlined" disabled>Claim after launch</button></article>)}</div><details><summary>Holder eligibility · Separate from SOL commitments</summary><p>Hold at least 0.05% of a parent’s supply at its published snapshot to qualify for that community’s reserve. Each community receives half of the 10% parent allocation.</p><p>Claimable Shartcoin amounts require confirmed parent mints, token supply and a verified wallet snapshot. Claims open only after launch and reserve funding. SOL participation and excess refunds are separate.</p></details></section>


   <details className="launch-details"><summary>Dev allocation · 3%</summary><p>1% unlocks when the pool launches. The remaining 2% vests linearly over three calendar months, with no cliff.</p></details><LegacyEscrow identity={identity} onSignIn={onSignIn}/>
   <CoinUpdates profile={profile} posts={posts} onAction={onAction} ready={ready}/>
   <details className="prelaunch-terms"><summary>Launch details</summary>{live?<><p>{net.live?'The escrow program holds your SOL on-chain.':net.name+' escrow holds test SOL on-chain.'} Funding closes {new Date(chain.data.deadlineUnix*1000).toLocaleString()}. If the soft cap is missed, all commitments become refundable.</p><p>Accepted SOL funds half the opening pool; Shartcoin supplies the other half. The total pool range is ${policy.softPoolUsd.toLocaleString('en-GB')}–${policy.poolUsd.toLocaleString('en-GB')}. SOL caps are fixed in the escrow: {sol(policy.softCap)}–{sol(policy.cap)} SOL.</p><p>Over the hard cap, allocations are proportional and excess SOL is refundable. Below the soft cap, the full amount is refundable. Refund processing can be triggered without the dev; unprocessed refunds can be claimed here.</p>{chain.data.launchDeadlineUnix&&<p>If launch is not completed by {new Date(chain.data.launchDeadlineUnix*1000).toLocaleString()}, the launch timeout refund path applies.</p>}<p className="escrow-address">Escrow: {chain.data.escrowAddress}</p><p className="escrow-address">Program: {chain.data.programId}</p></>:preview?<p>Sample commitments illustrate proportional allocations and refunds. No SOL is transferred by the preview controls.</p>:<p>Escrow configuration is loading or unavailable. Funding controls remain closed.</p>}</details>
  </div><aside className="commit-panel" id="shart-commit">  <div className="coin-banner"><img src={profile?.banner||"/assets/shart-cover.jpg"} alt="Shartcoin coin banner"/>{false&&<><span>FARTCOIN × BUTTCOIN</span><strong>Oh, Shartcoin.</strong></>}<div className="coin-socials">{[{key:'xUrl',label:'Shartcoin on X',Icon:XLogo},{key:'websiteUrl',label:'Shartcoin website',Icon:Globe}].map(({key,label,Icon})=>profile?.[key]?<a key={key} href={profile[key]} target="_blank" rel="noopener noreferrer" aria-label={label} title={label}><Icon size={20}/></a>:<button key={key} disabled aria-label={`${label} — not added yet`} title={`${label} — add a URL in Dev controls`}><Icon size={20}/></button>)}</div></div>
  <div className="prelaunch-heading"><img className="coin-logo" src={profile?.logo||"/assets/shart-pfp.png"} alt="Shartcoin logo"/><div><p className="eyebrow coin-parent-inline"><span className="parent-label">Parents</span><ParentIcon name="Fartcoin"/><span>Fartcoin</span><span aria-hidden="true">×</span><ParentIcon name="Buttcoin"/><span>Buttcoin</span></p><div className="coin-title-line"><h1>Shartcoin <span>$Shartcoin</span></h1></div></div><span className={"prelaunch phase-"+(fundingPhase||"open")}>{fundingPhase==='launched'?'Live':fundingPhase==='failed'?'Not launched':['settled','awaiting-launch'].includes(fundingPhase)?'Launching':'Prelaunch'}</span></div>

{live?<LocalCommitPanel chain={chain} identity={identity} onSignIn={onSignIn} onOpenCoin={chain.data?.phase==='launched'?()=>go('PostLaunch'):null}/>:(chain.error&&!live)?<><p className="eyebrow">STATUS</p><h2>Live status unavailable</h2><p className="small muted">The ledger did not answer. Nothing can be committed until it does.</p><button className="primary" onClick={chain.refresh}>Retry</button></>:preview?<><p className="eyebrow">COMMIT SOL</p><OpensIn data={chain.data}/><p className="small muted">{chain.data?.next?.opensAtUnix?'The commit box unlocks when the countdown reaches zero.':'The opening date will be announced here first. Nothing can be committed before then.'}</p><div className="commit-locked">
<label>Commitment amount · SOL<input inputMode="decimal" value="" disabled aria-label="Commitment amount in SOL (opens later)" placeholder="0.00"/></label><div className="amount-presets">{['1','5','10'].map(n=><button key={n} disabled>{n} SOL</button>)}</div>
<div className="your-split"><div><span>Estimated allocation</span><small>0 SOL committed</small></div><div className="personal-values"><span>Into pool<strong>0 SOL</strong></span><span>Excess refund<strong>0 SOL</strong></span></div><small>Final allocation at close</small></div>
<button className="primary" disabled>{chain.data?.next?.opensAtUnix?'Opens '+formatUtc(chain.data.next.opensAtUnix):'Not open yet'}</button></div></>:<CoinSkeleton variant="commit"/>}
  </aside></div>
 </section>;
}
