import {useRef} from 'react';
import {ArrowRight, ArrowLeft, Check, MagnifyingGlass, Plus, UploadSimple, PencilSimple, ImageSquare} from '@phosphor-icons/react';
import {draftError,parentLabel} from './model';
import './submission-builder.css';

function ParentMark({name}) {
  const src=name==='Fartcoin'?'/assets/parent-fartcoin.webp':name==='Buttcoin'?'/assets/parent-buttcoin.png':null;
  return src?<img className="builder-parent-mark" src={src} alt=""/>:<span className="builder-parent-mark builder-initial" aria-hidden="true">{name?.slice(0,2).toUpperCase()||'?'}</span>;
}
const stageNames=['Pick parents','Create your kid','Review & submit'];
export function SubmissionBuilder({draft,step,setStep,field,onChooseParent,onPickParent,upload,error,setError,saved,serviceReady,submitting,onSubmit,onLeave,onBrowse,onRules,onAmounts,identity}) {
  const heading=useRef(null);
  const parentReady=key=>['Fartcoin','Buttcoin'].includes(draft[key])||Boolean(draft.parentData?.[key]?.supported&&draft.parentData[key].mint===draft[key]);
  const parentsReady=parentReady('a')&&parentReady('b')&&draft.a!==draft.b;
  function move(target){
    if(target>step){const problem=!parentsReady?'Choose configured parents or look up their token mints. Your saved artwork and text are kept.':draftError(draft,target-1);if(problem){setError(problem);return;}}
    setError('');setStep(target);requestAnimationFrame(()=>heading.current?.focus());
  }
  const identityComplete=parentsReady&&!draftError(draft,2);
  const readyForReview=identityComplete&&draft.rights;
  return <section className="submission-builder" aria-label="Create a coin proposal">
    <div className="builder-header"><div><p className="builder-eyebrow">CREATE A COIN PROPOSAL</p><h1>Who’s the next kid?</h1><p>Choose two communities. Make their kid. Let KIDS holders vote.</p></div><button className="builder-text-link" onClick={onBrowse}>Explore the vote <ArrowRight size={18}/></button></div>
    <ol className="builder-steps" aria-label="Submission steps">{stageNames.map((name,i)=><li key={name}><button type="button" aria-current={step===i+1?'step':undefined} className={step===i+1?'is-current':step>i+1?'is-complete':''} onClick={()=>move(i+1)}><span>{step>i+1?<Check size={16} weight="bold"/>:i+1}</span><strong>{name}</strong></button></li>)}</ol>
    <div className="builder-workspace"><div className="builder-editor">
      <div className="builder-section-heading"><div><span className="builder-eyebrow">STEP {step} OF 3</span><h2 ref={heading} tabIndex={-1}>{step===1?'Start with the parents.':step===2?'Give your kid an identity.':'Ready for its first vote?'}</h2></div><span className="builder-step-count">0{step}</span></div>
      {step===1?<>
        <p className="builder-helper">Pick a community for each side. They must be different.</p>{!parentsReady&&<p className="builder-helper">Your saved draft is here. Choose supported parents below to continue; your artwork and text stay as they are.</p>}
        <div className="builder-parent-pair">{['a','b'].map((key,i)=><div className="builder-parent-slot" key={key}><span className="builder-eyebrow">PARENT {i+1}</span><button className="builder-parent-selected" onClick={()=>onPickParent(key)} aria-label={`Change parent ${i+1}: ${parentLabel(draft[key])}`}><ParentMark name={draft[key]}/><strong>{parentLabel(draft[key])}</strong><span>Change <PencilSimple size={14}/></span></button><p className="builder-parent-status">{draft.parentData?.[key]?'Mint lookup saved':['Fartcoin','Buttcoin'].includes(draft[key])?'Local test community':'Concept · choose a mint to submit'}</p><div className="builder-quick-picks" aria-label={`Quick choices for parent ${i+1}`}>{['Fartcoin','Buttcoin'].map(name=><button key={name} disabled={draft[key==='a'?'b':'a']===name} aria-pressed={draft[key]===name} onClick={()=>onChooseParent(key,name)}><ParentMark name={name}/>{name}</button>)}</div><button className="builder-token-search" onClick={()=>onPickParent(key)}><MagnifyingGlass size={16}/> Find another token</button></div>) }<span className="builder-pair-plus" aria-hidden="true"><Plus size={20}/></span></div>
        <details className="builder-explainer"><summary>How do parent rewards work?</summary><p>Each parent community receives 5% of the kid’s supply. Hold at least 0.05% of that parent’s supply at its snapshot to qualify.</p><button className="builder-text-link" onClick={onAmounts}>Check token amounts <ArrowRight size={16}/></button></details>
      </>:step===2?<>
        <div className="builder-name-fields"><label>Coin name<input autoComplete="off" maxLength={28} value={draft.name} placeholder="Give it a memorable name" onChange={e=>field('name',e.target.value)}/></label><label>Ticker<div className="builder-ticker-input"><span>$</span><input autoComplete="off" maxLength={10} value={draft.ticker} placeholder="TICKER" onChange={e=>field('ticker',e.target.value.toUpperCase())}/></div></label></div>
        <label className="builder-description">The story<textarea maxLength={180} rows={3} value={draft.description} placeholder="What happens when these two communities make a kid?" onChange={e=>field('description',e.target.value)}/><span>{draft.description.length}/180</span></label>
        <div className="builder-upload-row"><label className="builder-upload">{draft.art?<img src={draft.art} alt="Current coin artwork"/>:<ImageSquare size={34}/>}<span><strong>{draft.art?'Change coin artwork':'Add coin artwork'}</strong><small>PNG or WebP · up to 1.5 MB</small></span><UploadSimple size={22}/><input type="file" accept="image/png,image/webp" onChange={upload}/></label>{draft.art&&<button className="builder-text-link" onClick={()=>field('art','')}>Remove</button>}</div>
        <button className="builder-text-link" onClick={()=>field('art','/assets/sprout.png')}>Try sample artwork</button>
      </>:<>
        <div className="builder-review-rows"><div><span>Parents</span><strong>{parentLabel(draft.a)} × {parentLabel(draft.b)}</strong><button aria-label="Edit parents" onClick={()=>move(1)}>Edit</button></div><div><span>Your kid</span><strong>{draft.name} <small>${draft.ticker}</small></strong><button aria-label="Edit coin identity" onClick={()=>move(2)}>Edit</button></div><div><span>Launch terms</span><strong>Standard KIDS allocation</strong><button aria-label="View launch terms" onClick={onRules}>View</button></div></div>
        <div className="builder-after-submit"><strong>What happens next</strong><ol><li><span>1</span><div><b>Dev submits</b><small>Your proposal enters review.</small></div></li><li><span>2</span><div><b>KIDS holders vote</b><small>Approved proposals join a round.</small></div></li><li><span>3</span><div><b>Winner prepares to launch</b><small>Launch checks come before funding.</small></div></li></ol></div>
        <label className="builder-rights"><input type="checkbox" checked={draft.rights} onChange={e=>field('rights',e.target.checked)}/><span>I own or have permission to use this artwork.</span></label>
        {!identity?.owner&&<p className="builder-helper">You’ll sign in before submitting. Your draft is saved.</p>}
      </>}
      {error&&<p className="warning builder-error" role="alert">{error}</p>}
      <div className="builder-actions">{step>1&&<button className="builder-back" onClick={()=>move(step-1)}><ArrowLeft size={18}/> Back</button>}{step<3?<button className="primary" onClick={()=>move(step+1)}>{step===1?'Create your kid':'Review proposal'}<ArrowRight size={20}/></button>:<button className="primary" disabled={!serviceReady||submitting||!draft.rights||!identityComplete} onClick={onSubmit}>{submitting?'Submitting…':'Submit proposal'}<ArrowRight size={20}/></button>}</div>
      <div className="builder-save-row"><span aria-live="polite">{saved||'Your draft stays on this device'}</span><button className="builder-text-link" onClick={onLeave}>Save & leave</button></div>
    </div><aside className="builder-preview"><div className="builder-preview-label"><span>YOUR COIN PREVIEW</span><span className="builder-draft-badge">Draft</span></div><div className="builder-family-strip"><span><ParentMark name={draft.a}/>{parentLabel(draft.a)}</span><Plus size={16}/><span><ParentMark name={draft.b}/>{parentLabel(draft.b)}</span></div><div className="builder-preview-card"><div className={`builder-preview-art ${draft.art?'has-art':''}`}>{draft.art?<img src={draft.art} alt={`${draft.name||'Your kid'} artwork preview`}/>:<><ImageSquare size={42}/><span>Your kid goes here</span><button onClick={()=>move(2)}>Add its identity <ArrowRight size={16}/></button></>}</div><div className="builder-preview-copy"><h3>{draft.name||'Your next big idea'}</h3><span className="builder-preview-ticker">${draft.ticker||'TICKER'}</span><p>{draft.description||'Its name, artwork and story will appear here as you create it.'}</p></div></div><div className="builder-preview-checklist"><span className={parentsReady?'is-done':''}>{parentsReady?<Check size={15}/>:<span className="builder-check-dot"/>} Two communities</span><span className={identityComplete?'is-done':''}>{identityComplete?<Check size={15}/>:<span className="builder-check-dot"/>} Coin identity</span><span className={readyForReview?'is-done':''}>{readyForReview?<Check size={15}/>:<span className="builder-check-dot"/>} Ready for review</span></div><p className="builder-preview-footnote">Submitting creates a proposal, not a token.</p></aside></div>
  </section>;
}
