import test from 'node:test';import assert from 'node:assert/strict';import {standardProvider,discoverWallets,selectWallet,validateWalletChallenge,walletForOwner} from '../src/wallet-connection.mjs';import {disconnectAndSignOut} from '../src/wallet-sign-out.mjs';
test('injected alternatives deduplicate and require both signing capabilities',()=>{const provider={connect(){},signMessage(){},signTransaction(){}};assert.equal(discoverWallets({phantom:{solana:provider},solana:provider}).filter(w=>!w.install).length,1);assert.equal(discoverWallets({solflare:{connect(){}}}).filter(w=>!w.install).length,0);});
test('Standard adapter preserves exact messages and rejects account removal',async()=>{const account={address:'owner',features:['solana:signMessage','solana:signTransaction']};const wallet={accounts:[account],features:{'standard:connect':{connect:async()=>({accounts:[account]})},'solana:signMessage':{signMessage:async({message})=>[{signedMessage:message,signature:new Uint8Array(64)}]}}};const adapter=standardProvider(wallet);await adapter.connect();assert.equal((await adapter.signMessage(Uint8Array.of(1))).signature.length,64);wallet.accounts=[];await assert.rejects(adapter.signMessage(Uint8Array.of(1)),/changed/);});
test('challenge binds owner, origin, nonce and valid expiry',()=>{const now=Date.now(),c={id:'nonce',message:`kids.fun wants you to sign in with your Solana account:\nowner\n\nSign in to KIDS. This does not authorize transactions or move funds.\n\nURI: https://kids.fun\nVersion: 1\nNonce: nonce\nIssued At: ${new Date(now).toISOString()}\nExpiration Time: ${new Date(now+60000).toISOString()}`};validateWalletChallenge(c,'owner','https://kids.fun',now);assert.throws(()=>validateWalletChallenge(c,'other','https://kids.fun',now));assert.throws(()=>validateWalletChallenge({...c,message:c.message.replace('Expiration Time: ','Expiry: ')},'owner','https://kids.fun',now));});
test('reused sign-out revokes session despite stalled extension',async()=>{let forgot=false,revoked=false;const result=await disconnectAndSignOut({disconnect:()=>new Promise(()=>{}),forgetWallet:()=>forgot=true,logout:async()=>{revoked=true;}},{walletMs:5,sessionMs:50});assert.equal(result.walletDisconnected,false);assert.equal(result.sessionRevoked,true);assert.ok(forgot&&revoked);});
import {AccountStore} from '../server/account-store.mjs';import {withWalletDeadline,WALLET_DEADLINES} from '../src/wallet-connection.mjs';
test('server-issued challenge passes the client validator only for the issuing origin',()=>{const store=new AccountStore({origin:'https://kids.fun'});try{const owner='11111111111111111111111111111111';const c=store.challenge(owner);validateWalletChallenge(c,owner,'https://kids.fun');assert.throws(()=>validateWalletChallenge(c,owner,'https://kids-fun-flax.vercel.app'),/does not match/);assert.throws(()=>validateWalletChallenge({...c,id:'other'},owner,'https://kids.fun'),/does not match/);}finally{store.close();}});
test('stalled wallet prompts time out instead of leaving the page busy',async()=>{await assert.rejects(withWalletDeadline(new Promise(()=>{}),5,'Wallet connection'),e=>e.name==='TimeoutError'&&/timed out/.test(e.message));assert.equal(await withWalletDeadline(Promise.resolve(7),50,'x'),7);const saved=WALLET_DEADLINES.connectMs;WALLET_DEADLINES.connectMs=5;try{const [choice]=discoverWallets({solana:{connect:()=>new Promise(()=>{}),signMessage(){},signTransaction(){}}});await assert.rejects(choice.provider.connect(),/timed out/);}finally{WALLET_DEADLINES.connectMs=saved;}});
test('injected provider rejects a signature when the wallet switched accounts meanwhile',async()=>{const raw={publicKey:{toString:()=>'A'},connect:async()=>({publicKey:raw.publicKey}),signMessage:async()=>{raw.publicKey={toString:()=>'B'};return{signature:new Uint8Array(64)};},signTransaction:async t=>t};const [choice]=discoverWallets({phantom:{solana:raw}});await assert.rejects(choice.provider.signMessage(Uint8Array.of(1)),/account changed/);});
test('Standard change event drops a removed account before the next signature',async()=>{const account={address:'owner',features:['solana:signMessage','solana:signTransaction']};let listener;const wallet={accounts:[account],features:{'standard:connect':{connect:async()=>({accounts:[account]})},'standard:events':{on:(name,fn)=>{listener=fn;return()=>{listener=null;};}},'solana:signMessage':{signMessage:async({message})=>[{signedMessage:message,signature:new Uint8Array(64)}]}}};const adapter=standardProvider(wallet);await adapter.connect();assert.equal(adapter.publicKey.toString(),'owner');listener({accounts:[]});assert.equal(adapter.publicKey,null);await assert.rejects(adapter.signMessage(Uint8Array.of(1)),/changed/);await adapter.disconnect();assert.equal(listener,null);});
test('Phantom stays listed but paused until whitelisted; a saved Phantom choice is not restored',()=>{const provider={connect(){},signMessage(){},signTransaction(){}};const [choice]=discoverWallets({phantom:{solana:provider}});assert.equal(choice.name,'Phantom');assert.match(choice.paused,/reviewing kids\.fun/);assert.throws(()=>selectWallet(choice),/reviewing kids\.fun/);const [other]=discoverWallets({solflare:provider});assert.equal(other.paused,null);});
test('reconnect picks the signed-in account among several, and a mismatch names both accounts',async()=>{
 const a={address:'A'.repeat(32),features:['solana:signMessage','solana:signTransaction']},b={address:'B'.repeat(32),features:['solana:signMessage','solana:signTransaction']};
 const wallet={name:'Multi',accounts:[a,b],features:{'standard:connect':{connect:async()=>({accounts:[a,b]})},'solana:signMessage':{signMessage:async()=>[]},'solana:signTransaction':{signTransaction:async()=>[]}}};
 const provider=standardProvider(wallet);await provider.connect(b.address);assert.equal(provider.publicKey.toString(),b.address,'preferred account chosen');
 await provider.connect();assert.equal(provider.publicKey.toString(),a.address,'first usable account without a preference');
 globalThis.sessionStorage={getItem:()=>null,setItem(){},removeItem(){}};selectWallet({id:'standard:Multi',name:'Multi',wallet});
 assert.equal((await walletForOwner(b.address)).publicKey.toString(),b.address,'reconnects to the signed-in account');
 const single={name:'Single',accounts:[a],features:{'standard:connect':{connect:async()=>({accounts:[a]})},'solana:signMessage':{signMessage:async()=>[]},'solana:signTransaction':{signTransaction:async()=>[]}}};selectWallet({id:'standard:Single',name:'Single',wallet:single});
 await assert.rejects(walletForOwner(b.address),/active account is AAAA…AAAA, but you signed in with BBBB…BBBB/);
});

test('a direct link in a new tab finds the wallet again: stored choice in localStorage, else the wallet already holding the signed-in account',async()=>{
 const {restoreWalletForOwner,forgetWallet,discoverWallets}=await import('../src/wallet-connection.mjs');
 forgetWallet();
 const owner='OwnerAddress11111111111111111111111111111111';
 const store=new Map();globalThis.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};globalThis.sessionStorage={getItem:()=>null,setItem(){},removeItem(){}};
 const wallets=discoverWallets().filter(x=>!x.install);
 if(wallets.length){const w=wallets.find(x=>!x.paused);w.wallet.accounts=[{address:owner,features:['solana:signMessage','solana:signTransaction']}];assert.ok(restoreWalletForOwner(owner));assert.equal(store.get('kids-wallet'),w.id);forgetWallet();assert.equal(store.get('kids-wallet'),undefined);}
 else assert.throws(()=>restoreWalletForOwner(owner),/no wallet chosen/);
});

test('Phantom, Backpack and Jupiter are always listed in that order; a missing one is an install link, a detected one comes first',()=>{
 const provider={connect(){},signMessage(){},signTransaction(){}};
 const none=discoverWallets({});assert.deepEqual(none.map(w=>w.name),['Phantom','Backpack','Jupiter']);assert.ok(none.every(w=>w.install&&!w.provider&&!w.wallet));
 assert.equal(none[0].install,'https://phantom.com/download');assert.equal(none[2].install,'https://jup.ag/wallet');
 const some=discoverWallets({backpack:provider});assert.deepEqual(some.map(w=>[w.name,!!w.install]),[['Backpack',false],['Phantom',true],['Jupiter',true]]);
 const withPhantom=discoverWallets({phantom:{solana:provider},solflare:{connect(){},signMessage(){},signTransaction(){}}});assert.deepEqual(withPhantom.map(w=>w.name),['Phantom','Solflare','Backpack','Jupiter']);assert.match(withPhantom[0].paused,/reviewing kids\.fun/);assert.equal(withPhantom[0].install,undefined);
 assert.throws(()=>selectWallet(none[1]),/not installed/);
});
