import test from 'node:test';import assert from 'node:assert/strict';
import {Keypair,PublicKey,TransactionMessage,TransactionInstruction,VersionedTransaction,AddressLookupTableAccount,AddressLookupTableProgram} from '@solana/web3.js';
import {pinnedLookupTables,resolvePinnedLookups,pinLookupTables,pinCompiledLookups,provePinnedLookups,createPinnedLookupResolver} from './lookup-resolution.mjs';
import {lookupTableConnection,U64_MAX} from '../test/helpers/lookup-table-account.mjs';
const key=()=>Keypair.generate().publicKey;
function fixture(){
 const payer=Keypair.generate(),program=key(),tableKey=key(),accounts=Array.from({length:6},key);
 const table=new AddressLookupTableAccount({key:tableKey,state:{deactivationSlot:U64_MAX,lastExtendedSlot:10,lastExtendedSlotStartIndex:0,authority:payer.publicKey,addresses:accounts}});
 const ix=new TransactionInstruction({programId:program,keys:[{pubkey:accounts[1],isSigner:false,isWritable:true},{pubkey:accounts[4],isSigner:false,isWritable:false},{pubkey:payer.publicKey,isSigner:true,isWritable:true}],data:Buffer.from([4])});
 const message=new TransactionMessage({payerKey:payer.publicKey,recentBlockhash:key().toBase58(),instructions:[ix]}).compileToV0Message([table]);
 const pin=[{table:tableKey.toBase58(),addresses:accounts.map(String),writableIndexes:[1],readonlyIndexes:[4]}];
 const ledger=new Map([[String(tableKey),{authority:payer.publicKey,addresses:accounts,lastExtendedSlot:10}]]);
 return {payer,program,tableKey,accounts,table,message,pin,ledger};
}
test('pinned resolution shape: table identity, full contents and the selected indexes, nothing else',()=>{
 const f=fixture();
 assert.deepEqual(pinnedLookupTables(null),[]);assert.deepEqual(pinnedLookupTables([]),[]);
 const [t]=pinnedLookupTables(f.pin);assert.ok(t.key.equals(f.tableKey));assert.equal(t.state.addresses.length,6);
 const bad=[[f.pin[0],f.pin[0]],[f.pin[0],{...f.pin[0],table:String(key())},{...f.pin[0],table:String(key())}],[{...f.pin[0],extra:1}],[{table:f.pin[0].table,addresses:f.pin[0].addresses,writableIndexes:[1]}],[{...f.pin[0],table:'not-a-key'}],[{...f.pin[0],addresses:[]}],[{...f.pin[0],addresses:['x']}],[{...f.pin[0],writableIndexes:[6]}],[{...f.pin[0],writableIndexes:[-1]}],[{...f.pin[0],writableIndexes:[1,1]}],[{...f.pin[0],writableIndexes:[1],readonlyIndexes:[1]}],[{...f.pin[0],writableIndexes:[],readonlyIndexes:[]}],'pin',{}];
 for(const p of bad)assert.throws(()=>pinnedLookupTables(p),/Pinned lookup/,JSON.stringify(p).slice(0,80));
});
test('a message resolves only through a pin that names its tables, in order, with exactly its indexes',()=>{
 const f=fixture();
 const {tables,loadedAddresses}=resolvePinnedLookups(f.message,f.pin);
 assert.equal(tables.length,1);assert.deepEqual(loadedAddresses.writable.map(String),[String(f.accounts[1])]);assert.deepEqual(loadedAddresses.readonly.map(String),[String(f.accounts[4])]);
 const runtime=f.message.getAccountKeys({addressLookupTableAccounts:[f.table]}).accountKeysFromLookups;
 assert.deepEqual(loadedAddresses.writable.map(String),runtime.writable.map(String));assert.deepEqual(loadedAddresses.readonly.map(String),runtime.readonly.map(String));
 assert.throws(()=>resolvePinnedLookups(f.message,null),/differ from the pinned resolution/,'unpinned');
 assert.throws(()=>resolvePinnedLookups(f.message,[{...f.pin[0],table:String(key())}]),/table differs/);
 assert.throws(()=>resolvePinnedLookups(f.message,[{...f.pin[0],writableIndexes:[2]}]),/indexes differ/);
 assert.throws(()=>resolvePinnedLookups(f.message,[{...f.pin[0],readonlyIndexes:[4,5]}]),/indexes differ/);
 assert.throws(()=>resolvePinnedLookups(f.message,[{...f.pin[0],addresses:f.pin[0].addresses.slice(0,4)}]),/Pinned lookup index invalid/,'a pin shorter than its own indexes');
 const plain=new TransactionMessage({payerKey:f.payer.publicKey,recentBlockhash:key().toBase58(),instructions:[new TransactionInstruction({programId:f.program,keys:[],data:Buffer.from([4])})]}).compileToV0Message();
 assert.throws(()=>resolvePinnedLookups(plain,f.pin),/differ from the pinned resolution/,'a pin for a message that uses no table');
 assert.deepEqual(resolvePinnedLookups(plain,null).loadedAddresses,{writable:[],readonly:[]});
});
test('the ledger proof: finalized read, active, warm, keeper-owned or frozen, entries start with the pinned ones',async()=>{
 const f=fixture(),payer=f.payer.publicKey;
 const prove=(patch,options)=>{const ledger=new Map(f.ledger);const t={...ledger.get(String(f.tableKey)),...patch};ledger.set(String(f.tableKey),t);return provePinnedLookups(lookupTableConnection(ledger,options),f.pin,{payer});};
 const ok=await prove({});assert.equal(ok.slot,1000);assert.equal(ok.tables.length,1);
 assert.equal((await prove({addresses:[...f.accounts,key(),key()]})).slot,1000,'a table extended after the pin still starts with the pinned entries');
 assert.equal((await prove({authority:null})).slot,1000,'a frozen table is fine');
 await assert.rejects(prove({addresses:[...f.accounts.slice(0,3),key(),...f.accounts.slice(4)]}),/differs from the ledger/,'a pinned entry that is not on the ledger');
 await assert.rejects(prove({addresses:f.accounts.slice(0,5)}),/differs from the ledger/,'a ledger table shorter than the pin');
 await assert.rejects(prove({deactivationSlot:5n}),/deactivated/);
 await assert.rejects(prove({lastExtendedSlot:1000}),/not warm/,'extended in the finalized slot');
 await assert.rejects(prove({lastExtendedSlot:1500}),/not warm/);
 await assert.rejects(prove({authority:key()}),/foreign authority/);
 await assert.rejects(prove({owner:key()}),/not a lookup table/);
 await assert.rejects(provePinnedLookups(lookupTableConnection(new Map()),f.pin,{payer}),/not on the ledger/);
 await assert.rejects(prove({},{slot:0}),/slot unavailable/);
 assert.deepEqual(await provePinnedLookups(lookupTableConnection(new Map()),null,{payer}),{tables:[],slot:null});
 const c=lookupTableConnection(f.ledger);await provePinnedLookups(c,f.pin,{payer});assert.deepEqual(c.calls,[{key:String(f.tableKey),commitment:'finalized'}]);
});
test('the worker pins exactly the tables the compiler used, with the indexes it selected',async()=>{
 const f=fixture(),payer=f.payer.publicKey,other=key();
 const ledger=new Map(f.ledger);ledger.set(String(other),{authority:payer,addresses:[key(),key()],lastExtendedSlot:1});
 const read=await pinLookupTables(lookupTableConnection(ledger),[String(f.tableKey),String(other)],{payer});
 assert.equal(read.lookups.length,2);assert.deepEqual(read.lookups[0].addresses,f.accounts.map(String));assert.equal(read.slot,1000);
 const ix=new TransactionInstruction({programId:f.program,keys:[{pubkey:f.accounts[1],isSigner:false,isWritable:true},{pubkey:f.accounts[4],isSigner:false,isWritable:false},{pubkey:payer,isSigner:true,isWritable:true}],data:Buffer.from([4])});
 const message=new TransactionMessage({payerKey:payer,recentBlockhash:key().toBase58(),instructions:[ix]}).compileToV0Message(read.tables);
 const lookups=pinCompiledLookups(message,read);
 assert.deepEqual(lookups,f.pin,'the unused second table is not pinned');
 // Round trip: what the worker pinned is what the signer resolves and proves, and what the runtime would load.
 const resolved=resolvePinnedLookups(message,lookups);assert.deepEqual(resolved.loadedAddresses.writable.map(String),[String(f.accounts[1])]);assert.deepEqual(resolved.loadedAddresses.readonly.map(String),[String(f.accounts[4])]);
 assert.equal((await provePinnedLookups(lookupTableConnection(ledger),lookups,{payer})).slot,1000);
 const runtime=message.getAccountKeys({addressLookupTableAccounts:resolved.tables}).accountKeysFromLookups;assert.deepEqual(runtime.writable.map(String),resolved.loadedAddresses.writable.map(String));assert.deepEqual(runtime.readonly.map(String),resolved.loadedAddresses.readonly.map(String));
 const twoTables=new TransactionInstruction({programId:f.program,keys:[{pubkey:f.accounts[1],isSigner:false,isWritable:true},{pubkey:ledger.get(String(other)).addresses[0],isSigner:false,isWritable:false}],data:Buffer.from([4])});
 const both=new TransactionMessage({payerKey:payer,recentBlockhash:key().toBase58(),instructions:[twoTables]}).compileToV0Message(read.tables);
 const pinnedBoth=pinCompiledLookups(both,read);assert.deepEqual(pinnedBoth.map(l=>l.table),both.addressTableLookups.map(l=>String(l.accountKey)),'two tables pinned in message order');
 assert.equal((await provePinnedLookups(lookupTableConnection(ledger),pinnedBoth,{payer})).slot,1000);
 const foreign=new AddressLookupTableAccount({key:key(),state:{deactivationSlot:U64_MAX,lastExtendedSlot:0,lastExtendedSlotStartIndex:0,authority:undefined,addresses:[f.accounts[1]]}});
 const stray=new TransactionMessage({payerKey:payer,recentBlockhash:key().toBase58(),instructions:[ix]}).compileToV0Message([foreign]);
 assert.throws(()=>pinCompiledLookups(stray,read),/not read/);
 await assert.rejects(pinLookupTables(lookupTableConnection(ledger),[String(f.tableKey),String(f.tableKey)],{payer}),/Duplicate/);
 await assert.rejects(pinLookupTables(lookupTableConnection(ledger),[String(key())],{payer}),/not on the ledger/);
 await assert.rejects(pinLookupTables(lookupTableConnection(ledger),[1,2,3],{payer}),/Invalid lookup tables/);
 assert.deepEqual(await pinLookupTables(lookupTableConnection(ledger),[],{payer}),{lookups:[],tables:[],slot:null});
});
test('the signer resolver: only from the durable packet the request names, proved on the ledger, dependency failures tagged',async()=>{
 const f=fixture(),payer=f.payer.publicKey,op='a'.repeat(64);
 const rows=new Map();let registryFailure=null;
 const registry={operatorPackets:{get:async(operationId,attempt)=>{if(registryFailure)throw registryFailure;return rows.get(operationId+':'+attempt)??null;}}};
 const packet=(message,lookups,status='prepared')=>({status,prepared:{base64:Buffer.from(new VersionedTransaction(message).serialize()).toString('base64'),...(lookups?{lookups}:{})}});
 rows.set(op+':1',packet(f.message,f.pin));
 const ledger=new Map(f.ledger);let slot=1000,hang=false;
 const connection=lookupTableConnection(ledger,{slot:()=>slot});const base=connection.getAccountInfoAndContext;connection.getAccountInfoAndContext=(...a)=>hang?new Promise(()=>{}):base(...a);
 const resolve=createPinnedLookupResolver({registry,connection,payer,timeoutMs:50});
 const refs=f.message.addressTableLookups,packetRef={operationId:op,attempt:1};
 const loaded=await resolve(refs,{packetRef,message:f.message});
 assert.deepEqual(loaded.writable.map(String),[String(f.accounts[1])]);assert.deepEqual(loaded.readonly.map(String),[String(f.accounts[4])]);
 const refused=async(args,pattern)=>{await assert.rejects(resolve(refs,args),e=>{assert.match(e.message,pattern);assert.equal(e.dependency,undefined,'a deterministic refusal carries no dependency tag');return true;});};
 await refused({message:f.message},/packet reference required/);
 await refused({packetRef:{operationId:'x',attempt:1},message:f.message},/packet reference required/);
 await refused({packetRef:{operationId:op,attempt:2},message:f.message},/not current/);
 rows.set('b'.repeat(64)+':1',packet(f.message,f.pin,'expired'));await refused({packetRef:{operationId:'b'.repeat(64),attempt:1},message:f.message},/not current/);
 const otherMessage=new TransactionMessage({payerKey:payer,recentBlockhash:key().toBase58(),instructions:TransactionMessage.decompile(f.message,{addressLookupTableAccounts:[f.table]}).instructions}).compileToV0Message([f.table]);
 await refused({packetRef,message:otherMessage},/differs from the request/);
 rows.set('c'.repeat(64)+':1',packet(f.message,null));await refused({packetRef:{operationId:'c'.repeat(64),attempt:1},message:f.message},/differ from the pinned resolution/);
 rows.set('d'.repeat(64)+':1',packet(f.message,[{...f.pin[0],addresses:[String(key()),...f.pin[0].addresses.slice(1)]}]));await refused({packetRef:{operationId:'d'.repeat(64),attempt:1},message:f.message},/differs from the ledger/);
 const foreignPayer=Keypair.generate();const foreignMessage=new TransactionMessage({payerKey:foreignPayer.publicKey,recentBlockhash:key().toBase58(),instructions:TransactionMessage.decompile(f.message,{addressLookupTableAccounts:[f.table]}).instructions}).compileToV0Message([f.table]);
 rows.set('e'.repeat(64)+':1',packet(foreignMessage,f.pin));await assert.rejects(resolve(foreignMessage.addressTableLookups,{packetRef:{operationId:'e'.repeat(64),attempt:1},message:foreignMessage}),/payer differs/);
 ledger.get(String(f.tableKey)).deactivationSlot=5n;await refused({packetRef,message:f.message},/deactivated/);ledger.get(String(f.tableKey)).deactivationSlot=U64_MAX;
 registryFailure=Error('registry down');await assert.rejects(resolve(refs,{packetRef,message:f.message}),e=>e.dependency==='failure');registryFailure=null;
 registryFailure=Object.assign(Error('busy'),{code:'CAPACITY_WAIT'});await assert.rejects(resolve(refs,{packetRef,message:f.message}),e=>e.code==='CAPACITY_WAIT'&&!e.dependency);registryFailure=null;
 hang=true;await assert.rejects(resolve(refs,{packetRef,message:f.message}),e=>e.dependency==='timeout');hang=false;
 assert.deepEqual((await resolve(refs,{packetRef,message:f.message})).writable.map(String),[String(f.accounts[1])],'the same packet resolves again once the dependency is back');
});
