import {useEffect,useState} from 'react';
import {solAmount} from './campaign-adapter.mjs';
const pct=bps=>(bps/100)+'%';
export function CreatorQuote({quote,draft,busy,error,onAccept,onRefresh,onBack}){
 const [now,setNow]=useState(Date.now());useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 const q=quote.body,expired=now>=quote.expiresAt;
 return <section className="pl pl-creator"><div className="pl-head"><div><span className="pl-pill is-muted">Private localnet setup</span><h1>Review setup costs</h1><p>This accepts one saved draft. Wallet approvals follow separately.</p></div></div><div className="pl-panel">
  {draft&&<h2>{draft.name} · ${draft.symbol}</h2>}
  <div className="pl-rows"><div className="pl-row"><span>Accepted SOL caps</span><strong>{solAmount(q.terms.softCapLamports).exact} / {solAmount(q.terms.hardCapLamports).exact} SOL</strong></div><div className="pl-row"><span>Trading fee</span><strong>{q.terms.feePolicy.tradeFeeBps/100}%</strong></div><div className="pl-row"><span>Supply distribution</span><strong>{pct(q.terms.supplySplitBps.participants)} participants · {pct(q.terms.supplySplitBps.liquidity)} liquidity · {pct(q.terms.supplySplitBps.dev)} dev</strong></div><div className="pl-row"><span>Dev vesting</span><strong>{pct(q.terms.devVesting.immediateBps)} at launch · {pct(q.terms.devVesting.linearBps)} over {q.terms.devVesting.vestingMonths} months</strong></div></div>
  <p className="pl-creator-warning">Bounded setup estimate. The operating reserve below is a separate wallet approval after creation, and accepting does not open the launch to participants.</p>
  <div className="pl-rows">{q.costs.lines.map((line,i)=><div className="pl-row" key={i}><span>{line.item}</span><strong>{solAmount(line.lamports).exact} SOL</strong></div>)}<div className="pl-row"><span>Setup margin</span><strong>{solAmount(q.costs.marginLamports).exact} SOL</strong></div><div className="pl-row"><span>Estimated setup total</span><strong>{solAmount(q.costs.totalLamports).exact} SOL</strong></div><div className="pl-row"><span>Pool-initialization reserve (included)</span><strong>{solAmount(q.authorityFunding.amountLamports).exact} SOL</strong></div>{q.terms.operating&&<div className="pl-row"><span>Operating reserve (separate approval after creation)</span><strong>{solAmount(q.terms.operating.reserveLamports).exact} SOL</strong></div>}</div>
  {q.terms.operating&&<p className="pl-help-text">The operating reserve pays the keeper’s transactions for your campaign: settlement, launch, refunds and fee cycles. After launch {pct(q.terms.operating.refillBps)} of the treasury’s fee share refills it up to {solAmount(q.terms.operating.floorLamports).exact} SOL.{q.terms.operating.returnUnusedOnRefund?' Unused reserve returns to you if the launch ends in refunds.':''}</p>}
  <p className="pl-help-text">{expired?'This quote expired. Refresh before accepting.':'Quote expires in '+Math.max(0,Math.ceil((quote.expiresAt-now)/1000))+' seconds.'} Costs are reviewed again at each wallet approval.</p>
  {error&&<p role="alert">{error}</p>}<div className="pl-creator-actions"><button type="button" className="primary" disabled={busy||expired} onClick={onAccept}>Accept setup review</button><button type="button" disabled={busy} onClick={onRefresh}>Refresh quote</button><button type="button" disabled={busy} onClick={onBack}>Back to draft</button></div>
 </div></section>;
}
